### ISSUE TITLE
Two problems encountered in create junos_security_policy resource

### ISSUE THREAD

**Issue by xth0331** [jeremmfr/terraform-provider-junos#11]
# Terraform Version
0.12

I want to automate the addition of security policies, but I encountered two problems：
1. there is no address book in the resource
2. In the junos_security_policy resource, from_zone and to_zone two parameters are "Forces new resource".
Whether this project is only suitable for initialization

**Comment by jeremmfr** [comment]
Hi, 
1. Address book is in resource junos_security_zone
2. I don't understand the problem. "Force a new resource" is to destroy and recreate the resource if these parameters have changed after creation
