### ISSUE TITLE
Support Node specific apply-groups

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#120]
I completely agree with the comments in #66 about the use of apply groups.
In almost all cases different configuration sections should be made within code instead of apply groups.

One exception might be when it comes to node specific settings.
Since a Juniper cluster has one shared configuration, the only way to have node specific management interface settings applied is using apply groups.

Below some key settings that would be applicable in those cases.
Is this something that could be considered for a future release?

```
set apply-groups "${node}"
set groups node0 system host-name SRX-1
set groups node0 security log source-address 192.168.1.5
set groups node0 interfaces fxp0 unit 0 family inet address 192.168.1.5/24
set groups node0 interfaces fxp0 unit 0 family inet address 192.168.1.4/24 master-only

set groups node1 system host-name SRX-2
set groups node1 security log source-address 192.168.1.6
set groups node1 interfaces fxp0 unit 0 family inet address 192.168.1.6/24
set groups node1 interfaces fxp0 unit 0 family inet address 192.168.1.4/24 master-only
```

**Comment by jeremmfr** [comment]
Yes, in those cases, it's maybe neccessary.
There is also `backup-router` and more in this group.
I'll take care of adding special resource to configure `group (re|node)(0|1)`.
