### ISSUE TITLE
Create resource junos_protocol_evpn

### ISSUE THREAD

**Issue by dejongm** [jeremmfr/terraform-provider-junos#131]
A new resource to facilitate a spine-leaf evpn vxlan deployment. The resource code is mostly complete.
Schema is as follows:
```
                Schema: map[string]*schema.Schema{
                        "encapsulation": {
                                Type:   schema.TypeString,
                                Required: true,
                                ValidateFunc: validation.StringInSlice([]string{"mpls","vxlan"}, false),
                        },
                        "multicast_mode": {
                                Type:   schema.TypeString,
                                Optional: true,
                                ValidateFunc: validation.StringInSlice([]string{"ingress-replication"}, false),
                        },
                        "routing_instance": {
                                Type:   schema.TypeString,
                                Optional: true,
                                Default: defaultWord,
                                ValidateDiagFunc: validateNameObjectJunos([]string{}, 64),
                        },
                        "route_distinguisher": {
                                Type:             schema.TypeString,
                                Required:         true,
                        },
                        "vrf_import": {
                                Type:     schema.TypeList,
                                Optional: true,
                                MinItems: 1,
                                Elem:     &schema.Schema{Type: schema.TypeString},
                        },
                        "vrf_export": {
                                Type:     schema.TypeList,
                                Optional: true,
                                MinItems: 1,
                                Elem:     &schema.Schema{Type: schema.TypeString},
                        },
                        "vrf_target": {
                                Type:             schema.TypeString,
                                Optional:         true,
                        },
                        "vtep_source_interface": {
                                Type:     schema.TypeString,
                                Optional: true,
                        },

                },
```

The last five options reside in switch-options, but you cannot configure protocol evpn without setting route-distinguisher, vtep-source-interface and one of vrf_import, vrf_target within the switchoptions stanza. They all need to be committed at the same time.

**Comment by jeremmfr** [comment]
Do you have an example of the junos configuration that this will generate ?

**Comment by dejongm** [comment]
Yes...
set protocol evpn encapsulation vxlan
set protocol evpn multicast mode ingress-replication
set switch-options route-distinguisher 1.1.1.1:1
set switch-options vrf-import [PS01, PS02]
set switch-options vrf-target target:9999:9999
set switch-options vtep-source-interface lo0.0

**Comment by jeremmfr** [comment]
`vtep-source-interface` is not necessarily used only by the evpn protocol. He should be in another new resource `switch_options`
`multicast_mode` has only one choice, the argument should be a boolean `multicast_mode_ingress_replication`
I let you propose an MR

**Comment by dejongm** [comment]
I wanted to keep multicast_mode a block in case the feature set changes on the Junos platform. Thoughts?

**Comment by jeremmfr** [comment]
Ok, the Juniper [doc](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/multicast-mode-evpn-edit-routing-instances.html) indicates another possible choice

**Comment by jeremmfr** [comment]
Ok after 4 months, I will take care of adding this

**Comment by dejongm** [comment]
Sorry.. I've been pulled off to other priorities. I've created a pull request that covers this issue. Though, I haven't had the opportunity to clean it up. The code works. We've been using it in prod now for the last few months.
