### ISSUE TITLE
Scaling challenge with many resources

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#136]
With large amounts of resources defined i am running into some performance related challenges.
Most of the medium sized Juniper SRXes (like 300 series), take about 30 seconds for a commit to be applied with even a basic configuration. When the initial deployment completed, this is less of an issue since only changes applied.

Since every resource does its own commit, this quickly adds up. Although parallelism helps a little, it mainly slows down the commit locks since they the cannot be handled concurrently.

Would it make sense to allow the resource to apply their settings but only commit them at the end of the converge?
Any other suggestions?

Maybe commit check after each resource and commit at the end can help, my testing shows that this takes one third of the time of a commit

**Comment by jeremmfr** [comment]
Hi,
I already noticed early in the development of this provider that there could be a performance problem on some Junos models due to the too long commit.

So far I haven't found a suitable solution.
The first big problem is that Terraform does not inform the provider of when is the end of the resources to change (It would even be the end of the resources to change which only have dependencies resolved)

I keep thinking of potential solutions or workarounds

**Comment by universam1** [comment]
Rough idea - adding an optional parameter "NoCommitFlush" or similar that skips the commit on each resource  update, then perform the commit eventually via a finalizer hook.

**Comment by lukestu** [comment]
Possibly that optional parameter could trigger a commit-check for each resource update instead of a skip? commit-check is faster than commit and would provide error reporting...?

**Comment by rslemon** [comment]
Hi,

It would be very nice if long commit is supported.
I agree with the challenge detecting when is the end of the resources to change. So wondering if the following approach would be acceptable

1.  Introduce a parameter or environment variable like JUNOS_EXTERNAL_COMMIT
2.  Only when JUNOS_EXTERNAL_COMMIT is set as TRUE, 
2-1 **junos_xx resources** export candidate configuration from the function `netconfConfigSet` to somewhere. 
2-2 **junos_xx resources** does **nothing** to the target device(skip netconfCommit) 
2-3 **junos_xx resources** **update tfstate** as if it is applied
3.   The exported candidate configuration can be committed by using external script like below.
https://github.com/Juniper/go-netconf/blob/master/examples/juniper/get_system_information.go

This is a kind of configuration preparation mode to support long commit. 
Once long commit is done by 3, JUNOS_EXTERNAL_COMMIT variable can be removed and we can just continue to use this terraform-provider-junos provider further.

Please let me know how do you feel the approach above.
If needed, I can submit a pull request to give you the detailed idea above or willing to work in this regard.

Thank you for considering.

**Comment by jeremmfr** [comment]
Yes I have already thought about something like that, but it is more complex than that to set up. I am already working on it.
