### ISSUE TITLE
Create resource junos_global_policy with support for global policies

### ISSUE THREAD

**Issue by adrian884** [jeremmfr/terraform-provider-junos#138]
Hi, this is amazing work, thank you! I think it would greatly benefit from having support for global policies (i.e multiple src/dest zone), like the config set below:

```
set global policy Global-Allow-some-traffic match source-address Earth
set global policy Global-Allow-some-traffic match destination-address Clouds
set global policy Global-Allow-some-traffic match destination-address Moon
set global policy Global-Allow-some-traffic match application any
set global policy Global-Allow-some-traffic match from-zone Trust
set global policy Global-Allow-some-traffic match to-zone Zone1
set global policy Global-Allow-some-traffic match to-zone Zone2
set global policy Global-Allow-some-traffic then permit
set global policy Global-Allow-some-traffic then log session-init
set global policy Global-Allow-some-traffic then log session-close
```

I don't have any Go skills, but looking at the existing resource_security_policy.go file, looks like it could easily be adapted for the above. The policies would need to be identified by their names (not from/to-zone) and the set command build would start with "set global policy " instead of "set security policy from-zone ... to-zone ..."

Making the terraform definition something like this:

```
resource junos_global_policy "demo_policy" {
  policy {
    name                      = "allow_global_traffic"
    match_source_zone      = ["Trust"]
    match_destination_zone      = ["Zone1", "Zone2"]
    match_source_address      = ["Earth"]
    match_destination_address = ["Clouds", "Moon"]
    match_application         = ["any"]
  }
}
```

This would most likely need global addresses and sets, such as https://github.com/jeremmfr/terraform-provider-junos/issues/137

**Comment by jeremmfr** [comment]
It's a good proposal.
Global policies are still in security block so the name should be `junos_security_global_policy`
I will take care of adding the resource
