### ISSUE TITLE
host-inbound-traffic within interfaces settings with security zone

### ISSUE THREAD

**Issue by moz-uk** [jeremmfr/terraform-provider-junos#141]
my apologies if this is just a user error, but i think i am unable to achieve the below
```
set security zones security-zone INTERNET interfaces st0.0 host-inbound-traffic system-services ike
```
which is setting specific configuration for a named interface within the security zone, this allows fine control over the interfaces within zones for services/protocols

thankyou for this provider, i am using on SRX jeremmfr/junos v1.13.1

**Comment by jeremmfr** [comment]
Yes, you can only add `host-inbound-traffic` on the zone with `inbound_protocols` and `inbound_services` arguments in the `junos_security_zone` resource.
I'll take care of adding options in the `junos_interface_logical` resource for your need.

**Comment by moz-uk** [comment]
thankyou
