### ISSUE TITLE
Fix Address Book Entry Name Restrictions

### ISSUE THREAD

**Issue by tagur87** [jeremmfr/terraform-provider-junos#153]
It was found that we are getting failures when adding an address book entry using dots within the name

`svc.vpn.dev.internal.network invalid name (too long)`

Below is what junos says about allowed address names.
```
set security address-book global address abcd#abcd 1.1.1.1/32
error: address-name: 'abcd#abcd' : Must be a string beginning with a number or letter and consisting of letters, numbers, colons, periods, slash, dash and underscores
error : statement creation failed: address
```

I propose to create a new validation object for address names to match this format.

I can create it here soon.

**Comment by jeremmfr** [comment]
I rather think of reworking the existing function `validateNameObjectJunos`.
I'll take care of it
