### ISSUE TITLE
Feature request - Application Identification settings

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#158]
Would it be possible to start supporting some of the common settings to configure and enable AppID?

thank you for considering this!

```
set security forwarding-process enhanced-services-mode
set services application-identification download automatic start-time 10-14.02:00
set services application-identification download automatic interval 12
set services application-identification application-system-cache security-services
set services application-identification global-offload-byte-limit 8000
```

**Comment by jeremmfr** [comment]
I will take care of adding this.

**Comment by a-d-v** [comment]
To make application identification functionality usable, we would also need to support dynamic-applications parameter within security policies.

`set security policies from-zone untrust to-zone trust policy P1 match dynamic-application junos:MODBUS-READ-COILS`

**Comment by jeremmfr** [comment]
> To make application identification functionality usable, we would also need to support dynamic-applications parameter within security policies.
> 
> `set security policies from-zone untrust to-zone trust policy P1 match dynamic-application junos:MODBUS-READ-COILS`

Ok, I will add it too
