### ISSUE TITLE
Security Policy Ordering of rules

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#160]
With the creation of policies we are running into some limitations with the order of security policies.
Deny and allow rules often require a specific order to function properly.

Maybe an additional resource just for ordering of some specific rules could be a feasible option?

The insert before commands could be used to reorder created rules:
https://www.juniper.net/documentation/en_US/junos/topics/topic-map/security-reordering-policies.html

That way some rules that require a certain order (deny rule before an allow rule) could be defined with an explicit order.
Any suggestion?

**Comment by jeremmfr** [comment]
`policy` argument in `junos_security_policy` resource and `junos_security_global_policy` resource is an ordered list.
So if you change the order of `policy` blocks in your terraform config, the policy order changes on the Junos device.

**Comment by a-d-v** [comment]
Very well! thank you!
