### ISSUE TITLE
Support sampling config setup

### ISSUE THREAD

**Issue by rslemon** [jeremmfr/terraform-provider-junos#165]
Hi

Thank you for the great work regarding this provider.
If you like, could you please consider supporting sampling config setup like below?
> set interfaces reth1 unit 20 family inet sampling input
> set services flow-monitoring version-ipfix template ipfix-ipv4 ipv4-template
> set services flow-monitoring version-ipfix template ipfix-ipv4 flow-active-timeout 60
> set services flow-monitoring version-ipfix template ipfix-ipv4 flow-inactive-timeout 15
> set forwarding-options sampling instance vflow_instance input rate 200
> set forwarding-options sampling instance vflow_instance input max-packets-per-second 300
> set forwarding-options sampling instance vflow_instance family inet output flow-server 192.168.10.1 port 4739
> set forwarding-options sampling instance vflow_instance family inet output flow-server 192.168.10.1 version-ipfix template ipfix-ipv4
> set forwarding-options sampling instance vflow_instance family inet output flow-server 192.168.10.1 no-local-dump
> set forwarding-options sampling instance vflow_instance family inet output inline-jflow source-address 192.168.1.5
> 

Thanks again.
Ichi

**Comment by jeremmfr** [comment]
Yes, I will take care of adding this.
