### ISSUE TITLE
Connection Timeout Issues

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#167]
We are seeing some hard to understand issues with the terraform provider connecting to devices.
Especially during the terraform refresh the amount of open SSH connections are build up to very high levels, up to the point of failures to connect.

`error connecting to 192.168.10.2:830 - dial tcp 192.168.10.2:830: connect: connection timed out`

We have parallelism set to one. But it seems mainly that the SSH connections stay open in some cases.
Our two cents that SSH sessions are not closing properly with higher latency or the SSH connection timeout is low.

One workaround that helps is setting the idle timeout for SSH within the juniper to a very low value like 5 seconds.
This slows down the connection buildup a lot to not reach the juniper max SSH connection limit of 250.

No firewalls are within the path of terraform - juniper and it occurs with both vSRX and hardware junipers.
Any suggestions or ideas?

**Comment by jeremmfr** [comment]
I haven't been able to reproduce the problem (for example with 300 junos_static_route resources I always stay at 10 simultaneous connections when run `terraform refresh` with default parallelism).

What is the version of provider used ?
How many resources do you have by type of resource ?
Where do you see the huge number of open SSH connections ?

**Comment by a-d-v** [comment]
After more research and troubleshooting it might have been a issues with a specific Juniper firmware we were using. Sorry for the noise.
