### ISSUE TITLE
Feature Request: Add SNMP Support

### ISSUE THREAD

**Issue by Cidotis** [jeremmfr/terraform-provider-junos#170]
Hello, Thank you again for the nice work on this provider.

This is a feature request to add SNMP configuration support to the provider.
I'm looking for the ability to configure the following:
```
set snmp community _community-name_ authorization read-only
set snmp community _community-name_ clients 192.168.0.1/32
set snmp community _community-name_ clients 192.168.0.2/32
set snmp health-monitor
```

Junos References:
[set snmp health-monitor](https://www.juniper.net/documentation/us/en/software/junos/network-mgmt/topics/ref/statement/health-monitor-edit-snmp.html)
[set snmp community](https://www.juniper.net/documentation/us/en/software/junos/network-mgmt/topics/ref/statement/community-edit-snmp.html)

Thank you very much for considering this request.

**Comment by jeremmfr** [comment]
Yes, I will take care of adding this.
