### ISSUE TITLE
Add Cluster Node Specific IPv6 Address Support

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#177]
Thanks for implementing the cluster node configuration in version 1.14. It seems to be working very well!
Can we also consider adding support for defining node specific ipv6 addresses?

```
set groups node0 interfaces fxp0 unit 0 family inet6 address fe80::21/64
set groups node0 interfaces fxp0 unit 0 family inet6 address fe80::20/64 master-only

```

**Comment by jeremmfr** [comment]
Ok, I will correct this oversight.
