### ISSUE TITLE
Add support for SQL and RSH alg

### ISSUE THREAD

**Issue by edpio19** [jeremmfr/terraform-provider-junos#182]
This is a request to add two additional ALGs to security: SQL and RSH.
I would like to be able to enable and disable these two.

```
set security alg sql disable
set security alg rsh disable
```

Junos reference:
[rsh](https://www.juniper.net/documentation/us/en/software/junos/alg/topics/ref/statement/security-edit-rsh.html)
[sql](https://www.juniper.net/documentation/us/en/software/junos/alg/topics/ref/statement/security-edit-sql.html)

I have the code ready.

Thank you for all your hard work on this provider!

**Comment by jeremmfr** [comment]
Ok for add this
