### ISSUE TITLE
Support for policy-rematch

### ISSUE THREAD

**Issue by Sha-San-P** [jeremmfr/terraform-provider-junos#185]
Is it possible to add support for policy-rematch?

```set security policies policy-rematch extensive```

Maybe with an `attributes-as-blocks`, like so:

```
resource junos_security_policy TEST {
  policy-rematch {
    extensive = true
  }
}
```

I would like to hear your opinion. Please assign to me if you agree, so I can work on this.
Thanks!

**Comment by jeremmfr** [comment]
This option is a static configuration need to be integrate in the special `junos_security` resource.
A new `policies` block should be added with this `policy_rematch` block :
```hcl
resource junos_security security {
  policies {
    policy_rematch {
     extensive = true
    }
  }
}
```
I attribute the issue to you.
