### ISSUE TITLE
Bug: Security Policy Dynamic Application requires application

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#188]
Thank you for the very nice work on this provider!
I noticed a small issue with applying match_dynamic_application in security policies. It seems to require also the match_application setting to be set. But that is not the case when applying such configuration using Juniper CLI.

`The argument "match_application" is required, but no definition was found.`

**Comment by jeremmfr** [comment]
How is the configuration when using Juniper CLI ?
`application` seems well required for me.
For example I have a warning when show candidate configuration :

```
# show security policies from-zone trust to-zone untrust
policy allow {
    match {
        source-address any;
        destination-address any;
        dynamic-application junos:web;
        ## Warning: missing mandatory statement(s): 'application'
    }
    then {
        permit;
    }
}
```

and a error when `commit check` :
```
# commit check
[edit security policies from-zone trust to-zone untrust policy allow]
  'match'
    Missing mandatory statement: 'application'
error: configuration check-out failed: (missing mandatory statements)

```

**Comment by a-d-v** [comment]
The below is configured on my Juniper in a global policy, without any warning alerts.

```
match {
    source-address any;
    destination-address any;
    dynamic-application junos:BITTORRENT;
}
then {
    permit;
}
```

**Comment by jeremmfr** [comment]
What is the model and version of your Junos device ?

**Comment by jeremmfr** [comment]
Ok, I found the source of the different behavior.
https://www.juniper.net/documentation/us/en/software/junos/security-policies/topics/topic-map/configuring-unified-policies.html#id-understanding-applications-in-unified-policies
I will correct that.
