### ISSUE TITLE
Decouple zone address books from security zone

### ISSUE THREAD

**Issue by zorro-fr24** [jeremmfr/terraform-provider-junos#192]
Hi,
  I have the situation where we have lots of pre-existing security zone address book items ( we don't use the global address book, and it appears you cannot use both at once )

What I am trying to achieve via terraform is to define services which have multiple vm instances, and automatically configure policies, address book sets and address entries against those services.

This doesn't appear to be possible with the current structure where address books are one of many resource blocks contained within a security zone ( I cannot define a single address book/set without also defining the zone and all of its other addresses )

Do you think it would be worthwhile to have something like:

- _junos_security_zone_address_book_ which defines a single address entry that can be attached to a _junos_security_zone_ and optionally a pre-existing address_book_set
- _junos_security_zone_address_book_set_ which also attaches to a _junos_security_zone_  and can optionally attach a list of _junos_security_zone_address_ resources.

example:
```
resource junos_security_zone_address "demo_address" {
    name = "DemoAddressIdentifier"
    network = "192.0.2.10/32"
    zone = "MyZone"
    # address_set = "DemoAddressSet"
}

resource junos_security_zone_address_set "demo_address_set" {
    name = "DemoAddressSet"
    addresses = junos_security_zone_address.demo_address.*.name
    zone = "MyZone"
}
```

Thanks!

**Comment by jeremmfr** [comment]
The goal of integrating the `address_book` into the `zone` was to not generate as many commits as it does address and address-set, but indeed this can be restrictive for dynamic management.

I will take care of adding : 
- an argument to the `junos_security_zone` so that the `address-book` part can be managed separately
- create resources to manage each address and address-set
But I think I can't set the `address_set` argument to the` address` resource as proposed because it will conflict with the `address_set` resource.

It will be necessary to be careful, this will generate a lot more commits and the 2 ways of creating the addresses and address-sets (inside zone and singly) will be exclusive.

**Comment by zorro-fr24** [comment]
thanks @jeremmfr - I wasn't 100% sure about the attachment of address_set from within address resources anyway, I can definitely live without it!
I look forward to your other suggestions - cheers!

**Comment by zorro-fr24** [comment]
I just tested this today, and it looks like it fulfils our needs perfectly, thanks!

We are however seeing an issue when trying to destroy addresses and add and destroy address sets.  The plan applies are failing due to what I think is a warning returned by our SRX 1500s for an unrelated configuration issue:

```
module.vm.junos_security_zone_book_address.demo: Still destroying... [id=trust_-_my_test_address_2, 50s elapsed]
2021/05/06 14:45:08 [DEBUG] module.vm.junos_security_zone_book_address.demo: apply errored, but we're indicating that via the Error pointer rather than returning it: failed to netconf commit : XML syntax error on line 11: element <rpc-error> closed by </warning>
```
On the firewall side the commits are successfully applied, but terraform quits with the error:
```
Error: failed to netconf commit : XML syntax error on line 11: element <rpc-error> closed by </warning>
```

JUNOS Software Release [15.1X49-D160.2]
Terraform version: 0.14.7
JunOS Provider version: "main"

Test case:
```
resource junos_security_zone_book_address "demo" {
  name = "my_test_address"
  zone = "trust"
  cidr = "192.0.2.0/25"
}

resource junos_security_zone_book_address_set "demo_set" {
  name    = "my_test_address_set"
  zone    = "trust"
  address = junos_security_zone_book_address.demo.*.name
}
```

Let me know if you'd prefer I resubmit under a new ticket

Cheers

**Comment by jeremmfr** [comment]
The problem seems to come from the Junos device which does not respond a correct xml (Netconf message) after the commit.

The warnings should not be a problem cf #112

I haven't errors with this : 
```
resource "junos_security_zone" "trust" {
  name                          = "trust"
  address_book_configure_singly = true
}

resource "junos_security_zone_book_address" "demo" {
  name = "my_test_address"
  zone = junos_security_zone.trust.name
  cidr = "192.0.2.0/25"
}

resource "junos_security_zone_book_address_set" "demo_set" {
  name    = "my_test_address_set"
  zone    = junos_security_zone.trust.name
  address = junos_security_zone_book_address.demo.*.name
}
```
on
```
Hostname: vSRX
Model: vsrx
Junos: 15.1X49-D172.1
JUNOS Software Release [15.1X49-D172.1]
```
and a warning returned correctly via Terraform :
```
╷
│ Warning: mgd: requires 'wf_key_websense_ewf' license
│
│   on test.tf line 20, in resource "junos_security_zone" "trust":
│   20: resource "junos_security_zone" "trust" {
│
│ (and 2 more similar warnings elsewhere)
╵
```

**Comment by zorro-fr24** [comment]
Thanks for checking.

After trying to apply your test case:

```
Terraform will perform the following actions:

  # module.vm.junos_security_zone.trust will be created
  + resource "junos_security_zone" "trust" {
      + address_book_configure_singly = true
      + id                            = (known after apply)
      + name                          = "test"
    }

  # module.vm.junos_security_zone_book_address.demo will be created
  + resource "junos_security_zone_book_address" "demo" {
      + cidr = "192.0.2.0/25"
      + id   = (known after apply)
      + name = "my_test_address"
      + zone = "test"
    }

  # module.vm.junos_security_zone_book_address_set.demo_set will be created
  + resource "junos_security_zone_book_address_set" "demo_set" {
      + address = [
          + "my_test_address",
        ]
      + id      = (known after apply)
      + name    = "my_test_address_set"
      + zone    = "test"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.vm.junos_security_zone.trust: Creating...
module.vm.junos_security_zone.trust: Still creating... [10s elapsed]
module.vm.junos_security_zone.trust: Still creating... [20s elapsed]
module.vm.junos_security_zone.trust: Still creating... [30s elapsed]
module.vm.junos_security_zone.trust: Still creating... [40s elapsed]
module.vm.junos_security_zone.trust: Still creating... [50s elapsed]
module.vm.junos_security_zone.trust: Creation complete after 53s [id=test]
module.vm.junos_security_zone_book_address.demo: Creating...
module.vm.junos_security_zone_book_address.demo: Still creating... [10s elapsed]
module.vm.junos_security_zone_book_address.demo: Still creating... [20s elapsed]
module.vm.junos_security_zone_book_address.demo: Still creating... [30s elapsed]
module.vm.junos_security_zone_book_address.demo: Still creating... [40s elapsed]
module.vm.junos_security_zone_book_address.demo: Still creating... [50s elapsed]

Error: failed to netconf commit : XML syntax error on line 11: element <rpc-error> closed by </warning>

  on ../../../../modules/providers/vsphere/main.tf line 215, in resource "junos_security_zone_book_address" "demo":
 215: resource "junos_security_zone_book_address" "demo" {

```
I have attached the netconf log of the session

[netconf_xml_operations_2105070710.log](https://github.com/jeremmfr/terraform-provider-junos/files/6439778/netconf_xml_operations_2105070710.log)

Thanks

**Comment by zorro-fr24** [comment]
This looks suspicious to me:
```
May  7 07:11:14 [88375] Outgoing: <rpc-error>
May  7 07:11:14 [88375] Outgoing: <error-severity>warning</error-severity>
May  7 07:11:14 [88375] Outgoing: <source-daemon>
May  7 07:11:14 [88375] Outgoing: nsd
May  7 07:11:14 [88375] Outgoing: </source-daemon>
May  7 07:11:14 [88375] Outgoing: <message>
May  7 07:11:14 [88375] Outgoing: L2 global mode is switching mode, please add an interface in ethernet-switching mode, or change the L2 global mode!
May  7 07:11:14 [88375] Outgoing: </message>
May  7 07:11:14 [88375] Outgoing: </xnm:warning>
```
