### ISSUE TITLE
Security Policies application-services support

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#20]
Hi Jeremy,

yours terraform template looks great!
Do you see any possibilities to start supporting security policies application-services settings?

for example
<security policies> then permit application-services security-intelligence-policy Test-Policy
<security policies> then permit application-services utm-policy Test-Policy
<security policies> then permit application-services idp

thanks!
Arjen

**Comment by jeremmfr** [comment]
Hello,

I added new parameters for these functionalities #21, they are available in the new minor version v1.1.0 

Best regards,
Jérémy

**Comment by a-d-v** [comment]
Very nice!!!
