### ISSUE TITLE
Issue with security intelligence tls-profile

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#200]
I am trying to use the services security intelligence configuration with enrolling new devices that connect to JATP Cloud.
Because of the way JATP Cloud works, it is required to manually enroll JATP to retrieve the needed device certificates and tokens.

The Juniper enrollment process itself adds the below lines into the configuration

```
set services security-intelligence url https://cloudfeeds.sky.junipersecurity.net/api/manifest.xml
set services security-intelligence authentication tls-profile aamw-ssl
```

We have added these also in the resource, but the resource fails because of order.
The aamw-ssl cert needs to be available for this first not to error out.

If the above settings are not managed by the services resource, they are removed from the config on each apply.

A possible clean way to fix this would be adding a data source to read installed certificates.
This could be used to add a condition somewhat like

```
resource junos_services "services" {
  security_intelligence {
    authentication_token = (contains(data.certificates, "aamw-ssl") ? nil : aamw-ssl)
    url                  = "https://example.com/api/manifest.xml"
  }
}

```
thank you for considering this request!

**Comment by jeremmfr** [comment]
If the registration process, add authentication / url lines, I think it's easier to make the `authentication_token` / `authentication_tls_profile` / `url` arguments in possible attributes (read) mode if not set in Terraform config. So the rows will only be deleted when `security_intelligence` is not defined and overwritten the rows only if the corresponding arguments are defined in the Terraform config.
There is also that authentication is mandatory if the URL is defined :
```
user@terraform# set services security-intelligence url http://example.com

[edit]
user@terraform# commit check
error: Please config either Auth token or TLS profile
error: configuration check-out failed
```

**Comment by a-d-v** [comment]
Sounds good as well! thank you for the quick response
