### ISSUE TITLE
Feature request: system license

### ISSUE THREAD

**Issue by MerryPlant** [jeremmfr/terraform-provider-junos#205]
Hi jeremmfr,

I would like to add support for system licenses so I can do something like this:
```
set system license autoupdate url any_url password secret
set system license renew before-expiration 20 interval 24
```

I was thinking of implementing it like so:
```
license {
  autoupdate {
    url = "any_url"
    password = "secret"
  }
  renew_before_expiration = 20
  renew_interval = 24
}
```

What are your thoughts on this? 

I would love to work on this, please assign to me if you agree.

Reference [https://www.juniper.net/managing-licenses](https://www.juniper.net/documentation/en_US/release-independent/licensing/topics/topic-map/license-types.html#id-license)

Also, thank you for picking up web-management!

**Comment by jeremmfr** [comment]
Ok for add this

**Comment by jeremmfr** [comment]
> ```
>   autoupdate {
>     url = "any_url"
>     password = "secret"
>   }
> ```
I forgot, it should be simplified to have 
```hcl
autoupdate_url      = "any_url"
autoupdate_password = "secret"
```
