### ISSUE TITLE
Cluster Group Interface Primary IP setting

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#211]
While implementing clustering configuration i noticed that primary ip address attribute is not supported.

If possible, would you like to consider supporting this?

thank you!

```
set groups node1 interfaces fxp0 unit 0 family inet address 192.168.20.9/22 primary
set groups node1 interfaces fxp0 unit 0 family inet6 address fe80::9/64 primary
```

**Comment by jeremmfr** [comment]
Yes, I will take care of adding this.
