### ISSUE TITLE
Feature Request: Authentication using ssh-agent

### ISSUE THREAD

**Issue by micko** [jeremmfr/terraform-provider-junos#212]
Can you create a configuration option for "provider" to account for ssh-agent ? At moment if I do not set an authentication mechanism (i.e. if there is no "password" or "sshkey_pem" or "sshkeyfile") then I get an error:

"Error: no credentials/keys available"

thanks!

**Comment by micko** [comment]
here is a working diff...

diff --git a/junos/config.go b/junos/config.go
index c8d40ba..06dd404 100644
--- a/junos/config.go
+++ b/junos/config.go
@@ -16,6 +16,7 @@ type configProvider struct {
        junosIP                  string
        junosUserName            string
        junosPassword            string
+       junosSSHAgent            string
        junosSSHKeyPEM           string
        junosSSHKeyFile          string
        junosKeyPass             string
@@ -32,6 +33,7 @@ func (c *configProvider) prepareSession() (*Session, diag.Diagnostics) {
                junosPort:           c.junosPort,
                junosUserName:       c.junosUserName,
                junosPassword:       c.junosPassword,
+               junosSSHAgent:       c.junosSSHAgent,         
                junosSSHKeyPEM:      c.junosSSHKeyPEM,
                junosKeyPass:        c.junosKeyPass,
                junosGroupIntDel:    c.junosGroupIntDel,
diff --git a/junos/netconf.go b/junos/netconf.go
index 411146a..cc187a4 100644
--- a/junos/netconf.go
+++ b/junos/netconf.go
@@ -46,6 +46,7 @@ type commandXMLConfig struct {
 type netconfAuthMethod struct {
        Password       string
        Username       string
+       SSHAgent       string
        PrivateKeyPEM  string
        PrivateKeyFile string
        Passphrase     string
@@ -102,6 +103,19 @@ func newSessionFromNetconf(s *netconf.Session) (*NetconfObject, error) {
 func genSSHClientConfig(auth *netconfAuthMethod) (*ssh.ClientConfig, error) {
        var config *ssh.ClientConfig
 
+       if auth.SSHAgent == "true" {
+               config, err := netconf.SSHConfigPubKeyAgent(auth.Username)
+               if err != nil {
+                       return config, fmt.Errorf("failed to connect : %w", err)
+               }
+               config.Ciphers = append(config.Ciphers,
+                       "aes128-gcm@openssh.com", "chacha20-poly1305@openssh.com",
+                       "aes128-ctr", "aes192-ctr", "aes256-ctr",
+                       "aes128-cbc")
+               config.HostKeyCallback = ssh.InsecureIgnoreHostKey()
+
+               return config, nil
+       }
        if len(auth.PrivateKeyPEM) > 0 {
                config, err := netconf.SSHConfigPubKeyPem(auth.Username, []byte(auth.PrivateKeyPEM), auth.Passphrase)
                if err != nil {
diff --git a/junos/provider.go b/junos/provider.go
index 9442a3c..c9ca822 100644
--- a/junos/provider.go
+++ b/junos/provider.go
@@ -34,6 +34,11 @@ func Provider() *schema.Provider {
                                Optional:    true,
                                DefaultFunc: schema.EnvDefaultFunc("JUNOS_PASSWORD", nil),
                        },
+                       "sshagent": {
+                               Type:        schema.TypeString,
+                               Optional:    true,
+                               DefaultFunc: schema.EnvDefaultFunc("JUNOS_SSHAGENT", nil),
+                       },
                        "sshkey_pem": {
                                Type:        schema.TypeString,
                                Optional:    true,
@@ -180,6 +185,7 @@ func configureProvider(ctx context.Context, d *schema.ResourceData) (interface{}
                junosPort:                d.Get("port").(int),
                junosUserName:            d.Get("username").(string),
                junosPassword:            d.Get("password").(string),
+               junosSSHAgent:            d.Get("sshagent").(string),
                junosSSHKeyPEM:           d.Get("sshkey_pem").(string),
                junosSSHKeyFile:          d.Get("sshkeyfile").(string),
                junosKeyPass:             d.Get("keypass").(string),
diff --git a/junos/session.go b/junos/session.go
index c717c59..f852604 100644
--- a/junos/session.go
+++ b/junos/session.go
@@ -21,6 +21,7 @@ type Session struct {
        junosIP                string
        junosUserName          string
        junosPassword          string
+       junosSSHAgent          string
        junosSSHKeyPEM         string
        junosSSHKeyFile        string
        junosKeyPass           string
@@ -32,6 +33,9 @@ type Session struct {
 func (sess *Session) startNewSession() (*NetconfObject, error) {
        var auth netconfAuthMethod
        auth.Username = sess.junosUserName
+       if sess.junosSSHAgent == "true" {
+               auth.SSHAgent = "true"
+       }
        if sess.junosSSHKeyPEM != "" {
                auth.PrivateKeyPEM = sess.junosSSHKeyPEM
                if sess.junosKeyPass != "" {

**Comment by micko** [comment]
here is a working diff..

`diff --git a/junos/config.go b/junos/config.go
index c8d40ba..06dd404 100644
--- a/junos/config.go
+++ b/junos/config.go
@@ -16,6 +16,7 @@ type configProvider struct {
        junosIP                  string
        junosUserName            string
        junosPassword            string
+       junosSSHAgent            string
        junosSSHKeyPEM           string
        junosSSHKeyFile          string
        junosKeyPass             string
@@ -32,6 +33,7 @@ func (c *configProvider) prepareSession() (*Session, diag.Diagnostics) {
                junosPort:           c.junosPort,
                junosUserName:       c.junosUserName,
                junosPassword:       c.junosPassword,
+               junosSSHAgent:       c.junosSSHAgent,         
                junosSSHKeyPEM:      c.junosSSHKeyPEM,
                junosKeyPass:        c.junosKeyPass,
                junosGroupIntDel:    c.junosGroupIntDel,
diff --git a/junos/netconf.go b/junos/netconf.go
index 411146a..cc187a4 100644
--- a/junos/netconf.go
+++ b/junos/netconf.go
@@ -46,6 +46,7 @@ type commandXMLConfig struct {
 type netconfAuthMethod struct {
        Password       string
        Username       string
+       SSHAgent       string
        PrivateKeyPEM  string
        PrivateKeyFile string
        Passphrase     string
@@ -102,6 +103,19 @@ func newSessionFromNetconf(s *netconf.Session) (*NetconfObject, error) {
 func genSSHClientConfig(auth *netconfAuthMethod) (*ssh.ClientConfig, error) {
        var config *ssh.ClientConfig
 
+       if auth.SSHAgent == "true" {
+               config, err := netconf.SSHConfigPubKeyAgent(auth.Username)
+               if err != nil {
+                       return config, fmt.Errorf("failed to connect : %w", err)
+               }
+               config.Ciphers = append(config.Ciphers,
+                       "aes128-gcm@openssh.com", "chacha20-poly1305@openssh.com",
+                       "aes128-ctr", "aes192-ctr", "aes256-ctr",
+                       "aes128-cbc")
+               config.HostKeyCallback = ssh.InsecureIgnoreHostKey()
+
+               return config, nil
+       }
        if len(auth.PrivateKeyPEM) > 0 {
                config, err := netconf.SSHConfigPubKeyPem(auth.Username, []byte(auth.PrivateKeyPEM), auth.Passphrase)
                if err != nil {
diff --git a/junos/provider.go b/junos/provider.go
index 9442a3c..c9ca822 100644
--- a/junos/provider.go
+++ b/junos/provider.go
@@ -34,6 +34,11 @@ func Provider() *schema.Provider {
                                Optional:    true,
                                DefaultFunc: schema.EnvDefaultFunc("JUNOS_PASSWORD", nil),
                        },
+                       "sshagent": {
+                               Type:        schema.TypeString,
+                               Optional:    true,
+                               DefaultFunc: schema.EnvDefaultFunc("JUNOS_SSHAGENT", nil),
+                       },
                        "sshkey_pem": {
                                Type:        schema.TypeString,
                                Optional:    true,
@@ -180,6 +185,7 @@ func configureProvider(ctx context.Context, d *schema.ResourceData) (interface{}
                junosPort:                d.Get("port").(int),
                junosUserName:            d.Get("username").(string),
                junosPassword:            d.Get("password").(string),
+               junosSSHAgent:            d.Get("sshagent").(string),
                junosSSHKeyPEM:           d.Get("sshkey_pem").(string),
                junosSSHKeyFile:          d.Get("sshkeyfile").(string),
                junosKeyPass:             d.Get("keypass").(string),
diff --git a/junos/session.go b/junos/session.go
index c717c59..f852604 100644
--- a/junos/session.go
+++ b/junos/session.go
@@ -21,6 +21,7 @@ type Session struct {
        junosIP                string
        junosUserName          string
        junosPassword          string
+       junosSSHAgent          string
        junosSSHKeyPEM         string
        junosSSHKeyFile        string
        junosKeyPass           string
@@ -32,6 +33,9 @@ type Session struct {
 func (sess *Session) startNewSession() (*NetconfObject, error) {
        var auth netconfAuthMethod
        auth.Username = sess.junosUserName
+       if sess.junosSSHAgent == "true" {
+               auth.SSHAgent = "true"
+       }
        if sess.junosSSHKeyPEM != "" {
                auth.PrivateKeyPEM = sess.junosSSHKeyPEM
                if sess.junosKeyPass != "" {
`

**Comment by jeremmfr** [comment]
I had already planned to add an option (ciphers) on the SSH parameters and rework the connection to test the 2 key / password authentication methods. I will add the inclusion of keys through the SSH agent.
