### ISSUE TITLE
Routing options set forwarding-table

### ISSUE THREAD

**Issue by lynchs61** [jeremmfr/terraform-provider-junos#221]
I'm adding a `policy-statement` that I need to add to the `routing-options` `forwarding-table`.

I add the policy statement with something like the following:

```
resource "junos_policyoptions_policy_statement" "metallb-policy" {
  name = "metallb-${var.cluster_name}"
  from {
    protocol = ["bgp"]
    route_filter {
      route = cidrsubnet(var.k8dash_addr, 0, 0)
      option = "orlonger"
    }
  }
  then {
    load_balance = "per-packet"
  }
}
```

But then I need to add the following config:

`set routing-options forwarding-table export metallb-${var.cluster_name}`.

The `junos_routing_options` doesn't support this and I'm not sure how to get this working. I think I can use `junos_null_commit_file`, but I can't just give it a file because the set command is dynamic based on `var.cluster_name`.

If you could give some direction here I'd appreciate it.

**Comment by jeremmfr** [comment]
`routing-options forwarding-table` is not yet supported. I'll take care of adding this.

While waiting, you can use the `junos_null_commit_file` resource like this: 
```
resource "junos_policyoptions_policy_statement" "metallb-policy" {
  name = "metallb-${var.cluster_name}"
  from {
    protocol = ["bgp"]
    route_filter {
      route  = cidrsubnet(var.k8dash_addr, 0, 0)
      option = "orlonger"
    }
  }
  then {
    load_balance = "per-packet"
  }
}

# echo '' > empty
resource "junos_null_commit_file" "commit" {
  depends_on = [junos_policyoptions_policy_statement.metallb-policy]
  filename   = "empty"
  append_lines = [
    "set routing-options forwarding-table export metallb-${var.cluster_name}"
  ]
}
```

**Comment by lynchs61** [comment]
Awesome thanks for the quick reply. This looks like it works although I'm getting the following error now. The error happens after everything is successfully completed and all resources are created.

I'll look into it further and it might be something on my end, but I figured I'd post it here in case you know the problem.

```
│ Error: failed to xml unmarshal reply 
│ Non-existant dump device /dev/bo0s1b
│ <ok/>
│  : expected element type <commit-results> but have <ok>
│ 
│   on ../../../../static/terraform_modules/kube_cluster/main.tf line 68, in resource "junos_null_commit_file" "junos_setfile":
│   68: resource "junos_null_commit_file" "junos_setfile" {
```

**Comment by jeremmfr** [comment]
It's a bug of provider. I will create a new issue and fix that.
