### ISSUE TITLE
VLAN support for older devices (i.e. EX4200)

### ISSUE THREAD

**Issue by 0xDEADEAD** [jeremmfr/terraform-provider-junos#222]
Hey,

would it be possible to allow irb OR vlan  prefix on  junos_vlan to support older devices which currently cannot create vlans under the irb.* syntax but need to use vlan.* as their l3_interface?

For example junos_vlan
```
resource "junos_vlan" "this" {
  name         = "vlan_test"
  vlan_id      = 2
  l3_interface = "vlan.2"
}
```

And could you also let the fix from yesterday, mentioned in my issue https://github.com/jeremmfr/terraform-provider-junos/issues/217 ,  apply to the prefix vlan as well ?

This would be a huge lifesaver.

**Comment by jeremmfr** [comment]
Ok, I will take care of fix that.

**Comment by jeremmfr** [comment]
Resolve with v1.16.2

**Comment by 0xDEADEAD** [comment]
Seems to be working fine. Tested it a few seconds ago
