### ISSUE TITLE
Unable to destroy resource due to dependencies

### ISSUE THREAD

**Issue by lynchs61** [jeremmfr/terraform-provider-junos#227]
After the fix related to #221 I now have the following setup which causes a problem when trying to destroy the created resources.

```
resource "junos_policyoptions_policy_statement" "metallb-policy" {
  name = "metallb-${var.cluster_name}"
  from {
    protocol = ["bgp"]
    route_filter {
      route = cidrsubnet(var.k8dash_addr, 0, 0)
      option = "orlonger"
    }
  }
  then {
    load_balance = "per-packet"
  }
}

resource "junos_null_commit_file" "junos_setfile" {
  filename = "${path.module}/junos_commit_routing-options.txt" # empty file
  append_lines = [
    "set routing-options forwarding-table export ${junos_policyoptions_policy_statement.metallb-policy.name}"
  ]
}
```

Because of the the dependency, the policy will be created before it's put into the forwarding table export. But when destroying these resources, the policy is deleted **first**. This creates a problem because it tries to do a commit after deleting the policy but now the forwarding table is trying to export a policy that no longer exists. It fails with the error `Policy error: Policy metallb-kube100 referenced but not defined`. 

I'm not sure if this is a bug or if I'm setting this up wrong.

**Comment by jeremmfr** [comment]
`junos_null_commit_file` resource just run the lines sets.  
If you delete this resource, it has no effect on the configuration.  

So you can't delete `junos_policyoptions_policy_statement` resource without remove manually `set routing-options forwarding-table export` line.

**Comment by lynchs61** [comment]
Ah ok. I see. Is it possible to achieve the above configuration (add the policy-statement and then add that to the forwarding table export) in a way that can be created and destroyed with `terraform apply` and `terraform destroy` with no manual steps?

**Comment by jeremmfr** [comment]
> Ah ok. I see. Is it possible to achieve the above configuration (add the policy-statement and then add that to the forwarding table export) in a way that can be created and destroyed with `terraform apply` and `terraform destroy` with no manual steps?

You must wait the next release of provider to use new `forwarding_table`.`export` argument in `junos_routing_options` resource (see #226)

**Comment by lynchs61** [comment]
@jeremmfr - Looking at the documentation, `junos_routing_options` says:

> This resource should only be created once. It's used to configure static (not object) options in routing-options block. Destroy this resource has no effect on the Junos configuration.

So it looks like this resource have the same problem? Just wanted to confirm before I look for another way to accomplish this. 

Thanks!

**Comment by jeremmfr** [comment]
Yes, indeed, a simple destroy will not meet your needs.
Something more dynamic is needed, for example with the future release : 
```hcl
variable "k8dash_addr" {
  default = ""
  type    = string
}
variable "cluster_name" {
  default = "issue221"
  type    = string
}

resource "junos_policyoptions_policy_statement" "metallb-policy" {
  lifecycle {
    create_before_destroy = true
  }
  count = var.k8dash_addr == "" ? 0 : 1
  name  = "metallb-${var.cluster_name}"
  from {
    protocol = ["bgp"]
    route_filter {
      route  = cidrsubnet(var.k8dash_addr, 0, 0)
      option = "orlonger"
    }
  }
  then {
    load_balance = "per-packet"
  }
}

resource "junos_routing_options" "testacc_routing_options" {
  depends_on = [junos_policyoptions_policy_statement.metallb-policy]
  dynamic "forwarding_table" {
    for_each = var.k8dash_addr == "" ? [] : [1]
    content {
      export = junos_policyoptions_policy_statement.metallb-policy.*.name
    }
  }
}
```
and : 
- to add policy : 
```bash
terraform apply -var "k8dash_addr=10.0.0.0/24"
```
- to remove policy :
```bash
terraform apply
```

**Comment by lynchs61** [comment]
@jeremmfr  - Thank you for your response again. This answer however, isn't as useful because this junos config update is in the context of other resources that are being created. So I'd like to be able to just use `terraform apply` and `terraform destroy` normally rather than using `terraform apply` in two different ways.

If you have a minute, can you explain why `junos_routing_options` only configures "static (not object)" options. I'm assuming there's a good reason for this that I'd like to understand. Because really what I'd like is to be able to use it like any other resource with a normal create and destroy lifecycle.

Again thanks for you time with this and all the work you've done here!

**Comment by jeremmfr** [comment]
This `junos_routing_options` resource doesn't create a Junos object with an unique identifier (like a name or a combination of name, scope, etc.)
The resource configure the static options (not in a object with an identifier) in `routing-options` Junos block and must only be created once, so I didn't see any interest in removing the lines when destroy. The `destroy` should only occur if the resource has been created by mistake several times.

To meet your need , I'll reopen the issue to plan the add of an extra argument to throw a cleaning of lines when launch `destroy` of this resource.

**Comment by lynchs61** [comment]
Ok that sounds great.
Real quick though...  Now that I'm looking at this further I see that most of the top-level junos config elements are also static. Would it make sense to make `forwarding_table` an actual resource rather than an argument for `junos_routing_options`? Following the convention of the other resources, you would have `junos_routing_options` as static, and `junos_routing_options_forwarding_table` as a resource. In this regard, `junos_rib_group` would also become `junos_routing_options_rib_group` since it's a child of the routing options stanza in a junos config.

For consistency this seems like a better option, although I realize it a much bigger change (and a breaking change). But I figured I'd bring it up.

I can contribute some time to this refactor if you're interested. I don't have a ton of experience with Go programming but I could get up to speed here pretty quickly.

**Comment by jeremmfr** [comment]
Thanks but I prefer to stay on my idea.
