### ISSUE TITLE
Feature request: Support inactivity timeout setting for the junos application definition

### ISSUE THREAD

**Issue by edpio19** [jeremmfr/terraform-provider-junos#230]
Thank you for all the hard work on this provider!
Would it be possible to support the ```inactivity-timeout``` option for ```applications```?

```
set applications application junos-http inactivity-timeout 900
```

Juniper reference:
[application (Applications)](https://www.juniper.net/documentation/us/en/software/junos/security-policies/topics/ref/statement/application-edit-applications-srx.html)

Thank you for considering this!

**Comment by jeremmfr** [comment]
Yes, I will take care of adding this.
