### ISSUE TITLE
Feature request: system archival configuration

### ISSUE THREAD

**Issue by MerryPlant** [jeremmfr/terraform-provider-junos#231]
Hi jeremmfr,

Would it be possible to add the ``archival configuration`` option to ``system``?

```
set system archival configuration transfer-interval 14400
set system archival configuration archive-sites "scp://juniper-configs@10.0.123.104:/destination/directory" password "mypassword"
```
Juniper reference:
[https://www.juniper.net/...router-configuration-archiving.html](https://www.juniper.net/documentation/us/en/software/junos/cli/topics/task/junos-software-system-management-router-configuration-archiving.html)

Thanks again for considering and keep up the good work!

**Comment by jeremmfr** [comment]
Yes, I will take care of adding this.
