### ISSUE TITLE
Feature Request: Route Aggregation

### ISSUE THREAD

**Issue by metroshica** [jeremmfr/terraform-provider-junos#24]
We currently configure all of our vSRX 100% with this provider, including all our BGP configuration. However, we've found that we do not have the ability to create a route aggregations for our routing-instances. Looking through the existing objects, it seems like it would be very similar to the junos_static_route resource as they live in roughly the same place in the config with very similar arguments. Here is an example of our routing-options section on a vSRX, with the static route being created via the provider and the aggregate being done manually:

```routing-options {
    static {
        route 10.264.250.0/24 next-hop 10.264.250.17;
        route 0.0.0.0/0 next-hop 10.264.250.18;
    }
    aggregate {
        route 10.264.0.0/16 {
            preference 200;
        }
    }
}

**Comment by jeremmfr** [comment]
Hi,

I added new resource junos_aggregate_route for resolve your issue.
Look this release [v1.2.0](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.2.0)
