### ISSUE TITLE
Unable to destroy resources with "clean_on_destroy"

### ISSUE THREAD

**Issue by lynchs61** [jeremmfr/terraform-provider-junos#241]
With the new release of 1.17.0 we now have the ability to "clean on destroy" static resources. I have to following setup that uses this feature but it's causing an error.

```
resource "junos_bgp_group" "metallb_bgp_group" {
  name = "metallb-${var.cluster_name}"
  peer_as = var.metallb_peer_as
  local_address = "192.168.26.101"
  multihop = true
  bgp_multipath {}
}

resource "junos_bgp_neighbor" "metallb_bgp_neighbors" {
  for_each = {for host, val in var.hosts: host => val if val["type"] == "kubenode"}
  ip = element(split("/", each.value.net_addr), 0)
  group = junos_bgp_group.metallb_bgp_group.name
}

resource "junos_policyoptions_policy_statement" "metallb-policy" {
  name = "metallb-${var.cluster_name}"
  from {
    protocol = ["bgp"]
    route_filter {
      route = cidrsubnet(var.k8dash_addr, 0, 0)
      option = "orlonger"
    }
  }
  then {
    load_balance = "per-packet"
  }
}

resource "junos_routing_options" "routing_options" {
  clean_on_destroy = true
  forwarding_table {
    export = [junos_policyoptions_policy_statement.metallb-policy.name]
  }
}
```

When I try to destroy these resources however, I get the error:
`must define local autonomous system when enabling BGP`

I believe this is because `clean_on_destroy` is trying to delete the entire `routing_options` block and not just the `forwarding_table` `export` part that I've added. Can you confirm? If so, this doesn't work with my setup because, the `routing_options` block is already configured for other BGP groups and can't be deleted. Also, if my understanding is correct here, can you possibly offer a solution.

Thank you!

**Comment by jeremmfr** [comment]
The `clean_on_destroy` argument clean supported lines by the resource when it is destroyed, and `routing-options autonomous-system` is one of those (with `autonomous_system` argument). So when destroy the resource with `clean_on_destroy`, provider try to clean this line.
This is one of the reasons why by default destroy this resource has no effect on the Junos configuration. 
As I said in issue #227, this resource is only used to configure static elements in `routing-options` block and this resource should only be created **once**. So by default, destroy this resource has no interest.
In your case, it's like a second resource `junos_routing_options` had been created somewhere else with the `autonomous_system` argument and it shouldn't have happened.

So for your need this is a problem, but after some thought, and as I think the order of policies in `forwarding-table export` list doesn't really seem to matter, I will take care to prepare a second way to add a policy in `forwarding-table export` list. This can be done directly from the `junos_policyoptions_policy_statement` resource and created the resource `junos_routing_options` will not be necessary.

**Comment by lynchs61** [comment]
This is great thanks! You do great work here and I appreciate it.
