### ISSUE TITLE
Minor issue with escaping of some settings

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#251]
I am running into an issue with how some settings are escaped by the terraform provider.

For example, if setting SSH Ciphers to @openssh.com ciphers, Terraform never successfully converges.
```
      ~ services {
          ~ ssh {
              ~ ciphers                        = [
                  - "\"aes128-gcm@openssh.com\"",
                  - "\"aes256-gcm@openssh.com\"",
                  + "aes128-gcm@openssh.com",
                  + "aes256-gcm@openssh.com",
                ]
                # (1 unchanged attributes hidden)
            }
        }
```

Something similar happens with setting an announcement banner and special characters like &

```
        ~ announcement         = "ASITE &amp; BSITE" -> "ASITE & BSITE"
```
Any suggestion how this can be best handled?
thank you!

**Comment by jeremmfr** [comment]
These are provider bugs, I will take care of fix them.
