### ISSUE TITLE
Feature Request - Support for `set event-options policy`

### ISSUE THREAD

**Issue by Cidotis** [jeremmfr/terraform-provider-junos#252]
Hello,

Thanks for the great work on this provider.
I'm looking to add some event based command trigger on a few SRX according to https://www.juniper.net/documentation/us/en/software/junos/automation-scripting/topics/concept/junos-script-automation-event-notifications-and-policy-overview.html.

This would require support for ` set event-option policy` commands (https://www.juniper.net/documentation/us/en/software/junos/automation-scripting/topics/ref/statement/policy-edit-event-options.html).

My side I'm only looking at configuring the following:
```
set event-options policy POLICY_NAME events EVENT
set event-options policy POLICY_NAME then execute-commands commands "COMMAND"
```

Thank you very much.

**Comment by jeremmfr** [comment]
Yes, I will take care of adding this.
