### ISSUE TITLE
Feature Request: Support for UTM Webfiltering

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#26]
We are currently starting to manage our Juniper SRXes with the great Terraform provider you have build.
Some of the features we are heavily using are not yet supported.

Would it be possible to look into supporting the Juniper Enhanced webfiltering settings?
Below are some of the settings that would be very useful.

    set security utm custom-objects url-pattern Global_Whitelisted value http://*.google.com

    set security utm feature-profile web-filtering type juniper-enhanced
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" category Global_Whitelisted action log-and-permit
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" category Enhanced_Network_Errors action block
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" site-reputation-action very-safe permit 
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" site-reputation-action moderately-safe log-and-permit
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" site-reputation-action fairly-safe log-and-permit
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" site-reputation-action suspicious log-and-permit
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" site-reputation-action harmful block
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" default log-and-permit
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" custom-block-message "Blocked by Juniper"
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" fallback-settings default log-and-permit
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" fallback-settings server-connectivity log-and-permit
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" fallback-settings timeout log-and-permit
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" fallback-settings too-many-requests log-and-permit
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" timeout 3
    set security utm feature-profile web-filtering juniper-enhanced profile "Default Webfilter" no-safe-search

    set security utm utm-policy "Internal Clients" web-filtering http-profile "Default Webfilter"

thank you for considering!
Arjen

**Comment by jeremmfr** [comment]
Hi,

I added new resource : 
- junos_security_utm_custom_url_pattern
- junos_security_utm_policy
- junos_security_utm_profile_web_filtering_juniper_enhanced
for resolve your issue.

Look this release [v1.3.0](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.3.0)
