### ISSUE TITLE
Feature Request - Support for `set event-options generate-event`

### ISSUE THREAD

**Issue by Cidotis** [jeremmfr/terraform-provider-junos#267]
Hello,

Thank you very much for the work in https://github.com/jeremmfr/terraform-provider-junos/issues/252#issue-939717676 this is really helpful, however I found out I forgot one to request support for `set event-options generate-event`  https://www.juniper.net/documentation/us/en/software/junos/automation-scripting/topics/ref/statement/generate-event-edit-event-options.html

This is an example of what I would like to configure:
`set event-options generate-event testEvent time-of-day "10:42:00 +0000"`

The end goal is to be able to schedule operational commands as described in https://kb.juniper.net/InfoCenter/index?page=content&id=KB22795&cat=J_SERIES&actp=LIST

Please let me know if you can work on it or would like me to try to add support for this.

Thank you very much.

**Comment by jeremmfr** [comment]
Yes, I will take care of adding this.
