### ISSUE TITLE
ability to have multiple entries per policy statement term

### ISSUE THREAD

**Issue by moz-uk** [jeremmfr/terraform-provider-junos#277]
ability to have multiple entries per policy statement term

when i use multiple of the same term name although it adds them into the policy statement on the junos device as expected
if i do another terraform plan without changing anything then terraform says its going to change /remove existing entries and add them again. we add/remove to existing  terms quite a bit.

only just started to use this functionality within terraform, so dont know if its a "bug" from previous versions.

```
set policy-options policy-statement onprem-to-azure term term_1 from route-filter 192.168.0.0/24 exact
set policy-options policy-statement onprem-to-azure term term_1 from route-filter 192.168.1.0/24 exact
set policy-options policy-statement onprem-to-azure term term_1 from route-filter 192.168.2.0/24 exact
```

using latest  v1.20

thankyou

**Comment by jeremmfr** [comment]
Without Terraform config, I can't confirm, but I think you have added several times the `term` block with the same `name` value (`term_1`) for these blocks. You should only create one block per `term` name. 
So for your need, you have to repeat `route_filter` block inside `term` block, for example like this :
```terraform
resource "junos_policyoptions_policy_statement" "onprem-to-azure" {
  name = "onprem-to-azure"
  term {
    name = "term_1"
    from {
      route_filter {
        route  = "192.168.0.0/24"
        option = "exact"
      }
      route_filter {
        route  = "192.168.1.0/24"
        option = "exact"
      }
      route_filter {
        route  = "192.168.2.0/24"
        option = "exact"
      }
    }
    then {
      action = "accept"
    }
  }
}

```

**Comment by moz-uk** [comment]
@jeremmfr i have tested your layout and it works perfect thankyou :) 
thankyou for the lesson is formatting the code
