### ISSUE TITLE
Support Chassis Cluster Control Ports

### ISSUE THREAD

**Issue by arjenvri** [jeremmfr/terraform-provider-junos#304]
Would it be possible to support setting the cluster control ports in a future release?

https://www.juniper.net/documentation/us/en/software/junos/chassis-cluster-security-devices/topics/topic-map/security-chassis-cluster-control-plane-interfaces.html

This is a required setting for some higher end Juniper SRX devices.

thank you for considering

```
set chassis cluster control-ports fpc 1 port 0
set chassis cluster control-ports fpc 4 port 0
```

**Comment by jeremmfr** [comment]
The `control-ports` only seems available on certain models. I do not have access to this kind of equipment.
I will try to add something with the [doc](https://www.juniper.net/documentation/us/en/software/junos/chassis-cluster-security-devices/topics/ref/statement/chassis-edit-control-ports.html) but without being able to test, there may be errors.

**Comment by arjenvri** [comment]
Thank you! I will be happy to try it out!
