### ISSUE TITLE
Disabling Unused Interfaces

### ISSUE THREAD

**Issue by arjenvri** [jeremmfr/terraform-provider-junos#305]
Is there a way to disable interfaces?
I would like to disable interfaces that are not used per security best practices.

thank you for your great work on this very complete provider!

**Comment by jeremmfr** [comment]
As explained [here](https://registry.terraform.io/providers/jeremmfr/junos/latest/docs#interface-specifications), by default when the provider destroy a `junos_interface_physical` resource and the interface is always present (with `<get-interface-information>` netconf command) after remove all configuration, it disables the interface with
```
set description NC
set disable
```
or if the provider's argument `group_interface_delete` is set, with 
```
set apply-groups <group_interface_delete>
```
This behavior can be deactivated with `no_disable_on_destroy` argument on `junos_interface_physical` resource.

If there are empty interfaces (never used by a `junos_interface_physical` resource), it may be interesting to create and then destroy a resource for each of them to disable these interfaces or when prepare a new Junos device, a initial config on interfaces before use the provider :
```
wildcard range set interfaces ge-0/0/[0-7] disable description NC
```

**Comment by arjenvri** [comment]
Understood, my scenario would be unused interfaces that are never configured with terraform. As such the ideal solution from my point of view would be supporting the wildcard range interface disable with a resource. This would allow to keep undefined and unused interfaces disabled also after initial deployment.

**Comment by jeremmfr** [comment]
Ok for this case, I will create a special resource to disable (like when destroy resource `junos_interface_physical`) a physical interface that would not have any configuration.

However, to generate wildcard/range interface list, the Terraform functions (like [range](https://www.terraform.io/docs/language/functions/range.html), [for_each](https://www.terraform.io/docs/language/meta-arguments/for_each.html)) are the best way to do this.
