### ISSUE TITLE
Application timeout

### ISSUE THREAD

**Issue by ozid** [jeremmfr/terraform-provider-junos#308]
Hello,

here: https://registry.terraform.io/providers/jeremmfr/junos/latest/docs/resources/application

**inactivity_timeout (Optional, Number)
Application-specific inactivity timeout (4..86400 seconds).**

On junos you are able to set string "never". Maybe this could be supported?

Thanks

**Comment by jeremmfr** [comment]
Hi, it's an oversight. I will take care of adding an option for this case.
