### ISSUE TITLE
invalid name (bad character) in login_user

### ISSUE THREAD

**Issue by ozid** [jeremmfr/terraform-provider-junos#318]
Hello,

This:

```
resource junos_system_login_user "test_user" {
  name               = "test.user"
  uid                = "4008"
  class              = "super-user"
  authentication {
    ssh_public_keys    = ["ssh-rsa AAAA", ]
  }
}

```

ouput an error when running: terraform plan

 **Error: test.user invalid name (bad character)**

This is how i imported:

**terraform import junos_system_login_user.test_user test.user**

Any idea how it can be solved? my only solution is to rename the user on the juniper by replace "." with "_"

Thanks you

**Comment by jeremmfr** [comment]
Hello,

It's a bug of my provider, I will fix that quickly.
I relied on the cli error which does not seem correct.
```bash
user@srx# set system login user test#1
                                                                 ^
user-name: 'test#1': Must contain characters (alphanumerics, underscores or hyphens) beginning with an alphanumeric or an underscore character..
```
I will add the dot

**Comment by ozid** [comment]
Ok, thanks you :)
