### ISSUE TITLE
Terraform for +100 000 resources

### ISSUE THREAD

**Issue by ozid** [jeremmfr/terraform-provider-junos#322]
Hello,

First, thanks for all issues solved these last days :) 

I would like to ask your recommandation if you have a set of over 100 000 resources, i already try to optimize the number of resources but i think i hit the minimum as we have very strict policy.
Mostly they are security-zone-address-book. 

A simple plan for much less resources (+300) can take over 10minutes to run.

Do you have any optimization tips? 

Thanks you,

**Comment by ozid** [comment]
maybe get an answer: junos_null_commit_file

**Comment by jeremmfr** [comment]
Hello, 

To create resources, there is a workaround to push config in one commit with the argument of provider  [fake_create_with_setfile](https://registry.terraform.io/providers/jeremmfr/junos/latest/docs#argument-reference) and resource [junos_null_commit_file](https://registry.terraform.io/providers/jeremmfr/junos/latest/docs/resources/null_commit_file)  but **not** for others actions **read** / **update** / **destroy**.
Maybe you should separate your resources into several different configurations/states (example: for each scope) to reduce read commands when launching the plan command.

By default, the addresses in a zone's address book are managed directly on the `junos_security_zone` resource.
Using the `junos_security_zone_address_book` resources will generate many more Netconf commands and that is why it is not the default way to manage the address book.

**Comment by ozid** [comment]
Indeed, managing address from the zone is much more faster :) ill check the null_commit_file also.

Thanks :)
