### ISSUE TITLE
Run order question

### ISSUE THREAD

**Issue by ozid** [jeremmfr/terraform-provider-junos#328]
Hello,

If i create 2 resources: a policy and an address-book associated with this policy and run terraform, it create and commit the policy before the address-book:

 Error: netconf rpc [error]
│ [edit security policies from-zone myzone to-zone myotherzone]
│   'policy Allow'
│     Destination address or address_set (PC1) not found.

If i check directly on the juniper, the policy seem to be created even with this error.
Am i missing something?

Thanks

**Comment by jeremmfr** [comment]
Hello,

There is a dependency between the 2 resources (address in address-book must be created before policy). You must declare this dependency with Terraform, look at [Resource Dependencies](https://www.terraform.io/language/resources/behavior#resource-dependencies) in Terraform documentation.
