### ISSUE TITLE
Feature request: Support System Settings

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#33]
Supporting the management of Junos system settings would allow for NTP, Radius and logging to be managed by code.
This would be a great addition to the existing settings that can be managed as a starting point for management and hardening of larger amounts of Juniper devices.

```set system services ssh root-login deny
set system services ssh no-tcp-forwarding
set system services ssh protocol-version v2
set system services ssh ciphers aes256-ctr
set system services ssh ciphers aes256-cbc
set system services ssh macs hmac-sha2-512
set system services ssh macs hmac-sha2-256
set system services ssh key-exchange ecdh-sha2-nistp256
set system services ssh key-exchange ecdh-sha2-nistp384
set system services ssh key-exchange ecdh-sha2-nistp521
set system services ssh key-exchange group-exchange-sha2
set system services ssh client-alive-count-max 3
set system services ssh client-alive-interval 10
set system services ssh connection-limit 3
set system services ssh rate-limit 3
set system services netconf ssh`

set system name-server 8.8.8.8
set system name-server 8.8.4.4

set system radius-server 192.168.1.20 secret "$9$encryptedsecretstring"
set system radius-server 192.168.1.20 timeout 2
set system radius-server 192.168.1.20 retry 1

set system syslog archive size 5m
set system syslog archive files 3
set system syslog user * any emergency
set system syslog host 192.168.1.50 authorization any
set system syslog host 192.168.1.50 daemon warning
set system syslog host 192.168.1.50 ftp warning
set system syslog file interactive-commands interactive-commands info
set system syslog file messages any critical
set system syslog file messages authorization info
set system syslog file messages match "!(preauth)"
set system syslog file messages structured-data

set system ntp boot-server 192.168.1.60
set system ntp server 192.168.1.60
set system ntp server 192.168.1.61
```

**Comment by jeremmfr** [comment]
Hi,

Several 'system' parameters can't be defined as an object (parameters block differentiable with a unique identifier such as a 'name', 'address', a pair 'route' / 'instance', ...) as required by a Terraform resource.
But i think i can add few resources (ntp server, radius server, syslog file and host).
PR Soon :)

**Comment by jtague87** [comment]
@jeremmfr - Thanks for all your hard work on this project! Are you open to additional contributors on this projects? I would be willing to assist and contribute if you are open to it.

**Comment by jeremmfr** [comment]
Hi,

I added new resource : 
- junos_system_ntp_server
- junos_system_radius_server
- junos_system_syslog_host
- junos_system_syslog_file

for resolve your issue.

Look this release [v1.4.0](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.4.0)

**Comment by jeremmfr** [comment]
Look release [v1.6.0](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.6.0) for your issue
