### ISSUE TITLE
An issue with access to a device with a key protected by passphrase / Several feature request

### ISSUE THREAD

**Issue by AndriiPysmenko** [jeremmfr/terraform-provider-junos#337]
Hi,

**ISSUE:**

- The Terraform version - v1.1.4
- Provider version - 1.24.0
- The Junos device type and version - vSRX JUNOS 21.1R2-S2.1

Looks like there is an issue with access to a device with a key protected by a passphrase:

Terraform config:
```
provider "junos" {
  ip         = A.B.C.D
  port       = 22
  username   = terraform
  keypass    = "some key"
  sshkeyfile = "path to key"
}
```

The next error appears:
```
Error: failed to create new SSHConfig with file private key : ssh: this private key is passphrase protected
```

At the same time this key works ok if you try to connect to the device via ssh:

```
iac:/home/terraform$ ssh -i .ssh/terraform-key terraform@A.B.C.D
Enter passphrase for key '.ssh/terraform-key': 
Last login: Wed Feb  9 20:30:34 2022 from D.C.B.A
--- JUNOS 21.1R2-S2.1 Kernel 64-bit XEN JNPR-11.0-20211011.a9cfe96_buil
{primary:node0}
terraform@> 
```

The same key without passphrase protection works as expected. So looks like keypass parameter is ignored.

**FUTURE REQUESTS:**
1) This is a hidden function in Junos when you are trying to create a local user on the device with a password and without entering a password in interactive line:

```
set system login user admin authentication plain-text-password-value SOME_PASSWORD
```
This command will create a user with the required password without entering a password in the interactive line. This parameter will be very helpful in resource junos_system_login_user if you are plan to manage dozen unique devices with the same local user but a different password (no need to generate an encrypted_password for each device).

2) Add SNMPv3 support to junos_snmp resource:

```
set snmp view all oid .1 include
set snmp engine-id use-mac-address
set snmp v3 usm local-engine user test_read authentication-md5 authentication-password PASSWORD
set snmp v3 usm local-engine user test_read privacy-none
set snmp v3 vacm security-to-group security-model usm security-name test_read group test_read
set snmp v3 vacm access group test_read default-context-prefix security-model usm security-level authentication read-view all
set snmp v3 usm local-engine user test_write authentication-md5 authentication-password PASSWORD
set snmp v3 usm local-engine user test_write privacy-none
set snmp v3 vacm security-to-group security-model usm security-name test_write group test_write
set snmp v3 vacm access group test_write default-context-prefix security-model usm security-level authentication read-view all
set snmp v3 vacm access group test_write default-context-prefix security-model usm security-level authentication notify-view all
set snmp v3 vacm access group test_write default-context-prefix security-model usm security-level authentication write-view all
```

3) Add resource with protocol support

```
set protocols lldp interface all
set protocols lldp-med interface all
set protocols igmp-snooping vlan all
set protocols layer2-control bpdu-block
set protocols rstp interface all
set protocols rstp bpdu-block-on-edge
set protocols vstp vlan all
```

4) Update resource junos_firewall_filter with option `then packet-mode`:

```
set firewall family inet filter SOME_FILTER_NAME term SOME_TERM_NAME then packet-mode
```

5) Add resource with group support

```
set groups GROUP_NAME security policies from-zone <*> to-zone <*> policy permit match source-address any
set groups GROUP_NAME security policies from-zone <*> to-zone <*> policy permit match destination-address any
set groups GROUP_NAME security policies from-zone <*> to-zone <*> policy permit match application any
set groups GROUP_NAME security policies from-zone <*> to-zone <*> policy permit then permit
```

**Comment by jeremmfr** [comment]
> Hi,
> 
> **ISSUE:**
> 
>     * The Terraform version - v1.1.4
> 
>     * Provider version - 1.24.0
> 
>     * The Junos device type and version - vSRX JUNOS 21.1R2-S2.1
> 
> 
> Looks like there is an issue with access to a device with a key protected by a passphrase:
> 
> Terraform config:
> 
> ```
> provider "junos" {
>   ip         = A.B.C.D
>   port       = 22
>   username   = terraform
>   keypass    = "some key"
>   sshkeyfile = "path to key"
> }
> ```
> 
> The next error appears:
> 
> ```
> Error: failed to create new SSHConfig with file private key : ssh: this private key is passphrase protected
> ```
> 
> At the same time this key works ok if you try to connect to the device via ssh:
> 
> ```
> iac:/home/terraform$ ssh -i .ssh/terraform-key terraform@A.B.C.D
> Enter passphrase for key '.ssh/terraform-key': 
> Last login: Wed Feb  9 20:30:34 2022 from D.C.B.A
> --- JUNOS 21.1R2-S2.1 Kernel 64-bit XEN JNPR-11.0-20211011.a9cfe96_buil
> {primary:node0}
> terraform@> 
> ```
> 
> The same key without passphrase protection works as expected. So looks like keypass parameter is ignored.
> 
> **FUTURE REQUESTS:**
> 
>     1. This is a hidden function in Junos when you are trying to create a local user on the device with a password and without entering a password in interactive line:
> 
> 
> ```
> set system login user admin authentication plain-text-password-value SOME_PASSWORD
> ```
> 
> This command will create a user with the required password without entering a password in the interactive line. This parameter will be very helpful in resource junos_system_login_user if you are plan to manage dozen unique devices with the same local user but a different password (no need to generate an encrypted_password for each device).
> 
>     2. Add SNMPv3 support to junos_snmp resource:
> 
> 
> ```
> set snmp view all oid .1 include
> set snmp engine-id use-mac-address
> set snmp v3 usm local-engine user test_read authentication-md5 authentication-password PASSWORD
> set snmp v3 usm local-engine user test_read privacy-none
> set snmp v3 vacm security-to-group security-model usm security-name test_read group test_read
> set snmp v3 vacm access group test_read default-context-prefix security-model usm security-level authentication read-view all
> set snmp v3 usm local-engine user test_write authentication-md5 authentication-password PASSWORD
> set snmp v3 usm local-engine user test_write privacy-none
> set snmp v3 vacm security-to-group security-model usm security-name test_write group test_write
> set snmp v3 vacm access group test_write default-context-prefix security-model usm security-level authentication read-view all
> set snmp v3 vacm access group test_write default-context-prefix security-model usm security-level authentication notify-view all
> set snmp v3 vacm access group test_write default-context-prefix security-model usm security-level authentication write-view all
> ```
> 
>     3. Add resource with protocol support
> 
> 
> ```
> set protocols lldp interface all
> set protocols lldp-med interface all
> set protocols igmp-snooping vlan all
> set protocols layer2-control bpdu-block
> set protocols rstp interface all
> set protocols rstp bpdu-block-on-edge
> set protocols vstp vlan all
> ```
> 
>     4. Update resource junos_firewall_filter with option `then packet-mode`:
> 
> 
> ```
> set firewall family inet filter SOME_FILTER_NAME term SOME_TERM_NAME then packet-mode
> ```
> 
>     5. Add resource with group support
> 
> 
> ```
> set groups GROUP_NAME security policies from-zone <*> to-zone <*> policy permit match source-address any
> set groups GROUP_NAME security policies from-zone <*> to-zone <*> policy permit match destination-address any
> set groups GROUP_NAME security policies from-zone <*> to-zone <*> policy permit match application any
> set groups GROUP_NAME security policies from-zone <*> to-zone <*> policy permit then permit
> ```

Hi,

After tests, the origin of the issue with the passphrase is a bug to detect protected key in the module [github.com/jeremmfr/go-netconf](https://github.com/jeremmfr/go-netconf). I'll take care of fixing that.

For clarity, I will create dedicated issues for each feature request.

**Comment by jeremmfr** [comment]
New Issues :
1. #338 
2. #339 
3. #340 
4. #341 
5. #342

**Comment by AndriiPysmenko** [comment]
Thanks for your quick efforts to take a look at this.
