### ISSUE TITLE
Feature request: Assign interfaces to a security_zone resource

### ISSUE THREAD

**Issue by vcalmic** [jeremmfr/terraform-provider-junos#350]
Hello,

I am trying to create a terraform resource for this Junos CLI statement. However, I cannot find how in security_zone resource docs how to specify ID of the interface

This is my Junos CLI statement:
```
set security zones security-zone untrust interfaces ge-0/0/0.0 host-inbound-traffic system-services ike
set security zones security-zone trust interfaces ge-0/0/1.0
set security zones security-zone trust interfaces ge-0/0/2.0
```

Quick example here too: https://www.juniper.net/documentation/us/en/software/junos/multicast-l2/topics/topic-map/security-zones-and-security-policies-on-security-devices.html#d215e43__d70228e119

Thank you!

**Comment by jeremmfr** [comment]
Adding it to the `junos_security_zone` resource would produce a conflict between this resource and the `junos_interface_logical` resource.  
Workaround options should be introduced to avoid conflict.  
I don't see what point it would be to introduce it versus the complexity it would generate.

**Comment by vcalmic** [comment]
> Adding it to the `junos_security_zone` resource would produce a conflict between this resource and the `junos_interface_logical` resource. Workaround options should be introduced to avoid conflict. I don't see what point it would be to introduce it versus the complexity it would generate.

Understood. Thank you @jeremmfr !
