### ISSUE TITLE
Feature request: OSPF Authentication

### ISSUE THREAD

**Issue by vcalmic** [jeremmfr/terraform-provider-junos#356]
Add resource for supporting OSPF Authentication

```
set protocols ospf area 0.0.0.0 interface so-0/1/0 authentication simple-password PssWd4
```
```
set protocols ospf area 0.0.0.0 interface so-0/2/0 authentication md5 5 key PssWd8 
```

[Configuring OSPF Authentication](https://www.juniper.net/documentation/us/en/software/junos/ospf/topics/topic-map/configuring-ospf-authentication.html)

**Comment by ivignan** [comment]
That is exactly what I am looking for ! I bet the community would appreciate this being tackled sooner rather than later !

**Comment by jozeecp** [comment]
I've been looking for this feature. Definitely a must have to make the ospf resource block useful.

**Comment by jeremmfr** [comment]
I will take care of adding this.
