### ISSUE TITLE
Enhancement: add possibility of creating a logical interface in a disabled state

### ISSUE THREAD

**Issue by AndriiPysmenko** [jeremmfr/terraform-provider-junos#395]
Hi,

Please take a look at the possibility of creating a logical interface in a disabled state via resource junos_interface_logical:

```set interfaces reth0 unit xxxx disable```

**Comment by jeremmfr** [comment]
I don't really see the point but I'll take care of adding the option.

**Comment by AndriiPysmenko** [comment]
Thank you for taking this.

Few cases when this functionality is needed: 
1) when you are going to migrate the existing network from one device to another, you can prepare all needed configurations on a new device and disable the logic interface on a new device. In maintenance windows, you just need to disable the network on the old device and enable it on a new one. This help to minimize downtime during migration.
2) Temporarily disabled service for customers (internal/external)
