### ISSUE TITLE
SSH Key Not Working

### ISSUE THREAD

**Issue by exd42062** [jeremmfr/terraform-provider-junos#40]
I tried making a Netconf connection to one of my Juniper switches and got the following error.  Meanwhile,  I can login successfully with my SSH client using the same key.  Any help is greatly appreciated.

`terraform {

  required_providers {
    junos = {
      source = "jeremmfr/junos"
      version = "1.5.0"
    }
  }
}

variable "ipv4" {
 default = "10.91.60.2"
}

variable "key" {
 default = "/Users/eridavis/Documents/terraform-config/juniper/id_rsa_pem"
}

variable "user" {
 default = "local-admin"
}

provider "junos" {
  # Configuration options
  ip = var.ipv4
  sshkeyfile = var.key
  username = var.user
}
resource junos_interface "interface_switch_demo" {
  name         = "ge-0/0/5"
  description  = "interfaceSwitchDemo"
  trunk        = true
  vlan_members = ["100"]
}
`

**Comment by exd42062** [comment]
Here is the error I get.

![image](https://user-images.githubusercontent.com/44954211/94439677-b8007480-016e-11eb-8e25-4390a28e691b.png)

**Comment by exd42062** [comment]
I'm not sure if I am doing something wrong.  I am fairly new to Terraform and so maybe there is something I am missing?

**Comment by exd42062** [comment]
This is my connection when I test Netconf from my SSH client.

![image](https://user-images.githubusercontent.com/44954211/94447170-84761800-0177-11eb-83cf-c84cc141e52d.png)

**Comment by jeremmfr** [comment]
Hi,

Can you check file permissions of your key `/Users/eridavis/Documents/terraform-config/juniper/id_rsa_pem` ?

**Comment by jeremmfr** [comment]
Hi,
I withdraw my previous question, there is other error if provider can't acces key file.
Are you sure the ssh key is authorized on Junos device ? I don't see which key is used in SSH client test.
Since [v1.5.1](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.5.1), you can use a password instead of a key if you want.

**Comment by jeremmfr** [comment]
Without responses, I close this issue
