### ISSUE TITLE
Validate address objects references before applying

### ISSUE THREAD

**Issue by arjenvri** [jeremmfr/terraform-provider-junos#404]
I am making daily changes to security policies with the terraform junos provider.
This works fairly well for most of my use cases.

One thing I keep running into is small errors in configuration of security policies that only get noticed when applying.
Would it be possible to validate security policy address objects references in the plan phase?

Mainly
- Address objects referred to in security policies should exist in the terraform config
- Address objects referred to in address-sets should exist in terraform config

thank you for considering my request!

**Comment by jeremmfr** [comment]
Hi,

This provider uses the Terraform plugin [terraform-plugin-sdk/v2](https://github.com/hashicorp/terraform-plugin-sdk) which does not allow accessing to configs of other resources Terraform.

But even if it were, it would be a restriction to have to declare the entries of the address books in the same Terraform config as the policies.

For your case and if the entries of the address books are declared in the same Terraform config as the policies, you should rather add dependencies (with the meta-argument [depends_on](https://www.terraform.io/language/meta-arguments/depends_on) or with references to resources attributes) between resources that create/update the policies and the resources which create/update the addresses in address book.

For example :

```hcl
resource "junos_security_zone" "untrust" {
  name = "untrust"
}
resource "junos_security_zone" "trust" {
  name                          = "trust"
  address_book_configure_singly = true
}
resource "junos_security_zone_book_address" "demo" {
  lifecycle {
    create_before_destroy = true
  }
  name = "address1"
  zone = junos_security_zone.trust.name
  cidr = "192.0.2.0/25"
}
resource "junos_security_policy" "demo" {
  from_zone = junos_security_zone.trust.name
  to_zone   = junos_security_zone.untrust.name
  policy {
    name                      = "allow_trust"
    match_source_address      = [junos_security_zone_book_address.demo.name]
    match_destination_address = ["any"]
    match_application         = ["any"]
  }
}
```
