### ISSUE TITLE
Bug: Wrong dependency management between security_policy and application

### ISSUE THREAD

**Issue by vetal2409** [jeremmfr/terraform-provider-junos#408]
Let's imagine we have a terraform code with declared junos_security_policy  and application **A**.
The security policy depends on the application **A**

- When we apply this configuration - it works as expected (application **A** is created **before** security_policy)
- When we destroy this configuration - it also works as expected (application **B** is deleted **after** security_policy)

## The problem:
- When replacing application **A** with application **B**. The plan looks like 1 to add (application **B**), 1 to change (security policy applications changed to [**B**] and depends on it accordingly, and 1 to destroy (application **A**).

### Expected behavior
1. Create application **B**
2. Change security policy
3. Delete application **A**

### Actual behavior
1. Create application **B**
2. Delete application **A** - **fails here because security policy still uses application A**
3. _do not_ Change security policy

### Our use case
We have a solution where developers can set the SRX security policies in a convenient for them way (not the terraform syntax). One of the features there is the possibility to define security_policy with a set of protocols and ports instead of exact application names.
Then, based on this configuration we generate terraform code (with help of cdktf).

Let's name is as  "dynamic applications". Instead of defining every single application, we generate it dynamically.

To come over the error needed to create new applications, apply configuration then delete the old application and apply configuration again. It should not work in this way. As far as we have all these things automated there is no workarounds at all.

@jeremmfr Could you please look at this issue? Let me know if you need some clarification or help. Thanks!

**Comment by jeremmfr** [comment]
Hi,

It’s not really a bug, it’s an incompatibility between the order of resources operations by Terraform and the dependencies needed by Junos and the various resources of this provider.  

If you look this document [https://github.com/hashicorp/terraform/blob/main/docs/destroying.md](https://github.com/hashicorp/terraform/blob/main/docs/destroying.md#resource-replacement), you can see the order of create, update and delete operations by Terraform in relation to their dependencies. By default to avoid conflict, if a resource need to be destroy (replacement or disappeared from the configuration), it will be destroy before update of their dependencies.  

There is a method for changing the ordering of create and destroy operations, and it's with the `create_before_destroy` resource `lifecycle` attribute [https://www.terraform.io/language/meta-arguments/lifecycle](https://www.terraform.io/language/meta-arguments/lifecycle#create_before_destroy)  

In this case the destroy will be done after create and update operations.

A example with this Terraform config :

```hcl
resource "junos_security_policy" "intra_zone1" {
  lifecycle {
    create_before_destroy = true
  }

  from_zone = junos_security_zone.zone1.name
  to_zone   = junos_security_zone.zone1.name
  policy {
    name                      = "allow_app"
    match_source_address      = ["any"]
    match_destination_address = ["any"]
    match_application         = [junos_application.A.name]
  }
}

resource "junos_security_zone" "zone1" {
  name = "zone1"
}

resource "junos_application" "A" {
  name             = "A"
  protocol         = "tcp"
  destination_port = "22"
}
```

If you change `A` by `B` in the configuration, resource `A` will be destroyed after update of resource `intra_zone1` and not before.
