### ISSUE TITLE
Feature request: Application data source

### ISSUE THREAD

**Issue by vetal2409** [jeremmfr/terraform-provider-junos#409]
It would be nice to have the **junos_application** and **junos_application_set** data sources. The desired criteria to search are the **protocol** and **port**.

### Our use case
We have a solution where developers can set the SRX security policies in a convenient for them way (not the terraform syntax). One of the features there is the possibility to define security_policy with a set of protocols and ports instead of exact application names.
Then, based on this configuration we generate terraform code (with help of cdktf).

Let's name is as  "dynamic applications". Instead of defining every single application, we generate it dynamically.

But the problem is that Junos have a default list of applications and it potentially can be changed from version to version. We don't want our developers to care about this application and its existence. Sometimes, we can get an error because the application already exists. If we have some way to check the existence of the application we would create dynamic applications conditionally. The Data source should help us to solve the problem. Thanks!

**Comment by jeremmfr** [comment]
Hi 👋 

Yes, I think I can create a data source by searching the default applications (in `group junos-defaults applications`) and applications already created (in `applications`) and then filtering with multiple criteria.

I take care of creating this.
