### ISSUE TITLE
ssh using password instead of sshkeyfile

### ISSUE THREAD

**Issue by arvindkonar** [jeremmfr/terraform-provider-junos#41]
Hey folks, 
Is it possible to use just the username and password instead of sshkeyfile.
I tried to use a blank in sshkeyfile since its required but it still looks for a keyfile. Also, not sure keypass is same as password.

`provider "junos" {`
`        ip = "a.b.c.d"`
`        username = "root"`
`        keypass = "passwordilike"`
`        sshkeyfile = ""`
`}`

**Comment by jeremmfr** [comment]
Hi,

`keypass` is the passphrase for open ssh key file locked.
I will add `password` option for authentication without sshkeyfile.

**Comment by jeremmfr** [comment]
The new version [v1.5.1](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.5.1) allows to use a `password` field in provider configuration.

**Comment by arvindkonar** [comment]
Thanks. That was quick. I'll test it out.
