### ISSUE TITLE
Bug: Static NAT64 Rule

### ISSUE THREAD

**Issue by arjenvri** [jeremmfr/terraform-provider-junos#420]
I am trying to find the way to define the below NAT64 related junos config using this provider

`set security nat static rule-set nat64-LAB1014 rule ipv6-clients1 then static-nat inet`

Any suggestion how it can be done?
```
resource "junos_security_nat_static" "nat64" {
  name = "nat64_translation"
  from {
    type = "zone"
    value = [
      "trust"
    ]
  }
  rule {
    name                = "nat64_clients"
    destination_address = "64:ff9b::/96"
    then {
      type = "inet" # Specifies automatic translation of IPv6 addresses to IPv4 addresses (and vice versa).
    }
  }
}
```

**Error: missing routing_instance in rule nat64_clients with type = inet**

https://rtodto.net/how-do-nat64-and-dns64-work-in-ipv6-world-and-srx-config/

**Comment by jeremmfr** [comment]
Hi 👋 ,

The provider forces to have a routing instance with `then inet` but yes it shouldn't.
I'll take care of fixing that.

**Comment by arjenvri** [comment]
> Hi 👋 ,
> 
> The provider forces to have a routing instance with `then inet` but yes it shouldn't. I'll take care of fixing that.

Thank you so much!
