### ISSUE TITLE
Feature request: policy-statement to manage `as-path-unique-count` from directive.

### ISSUE THREAD

**Issue by xaque208** [jeremmfr/terraform-provider-junos#424]
### Description
I have the following policy-statement to restrict the routes accepted.
```
set policy-options policy-statement kubernetes term 0 from as-path-unique-count 2 orhigher
set policy-options policy-statement kubernetes term 0 then reject
```
I'd like to be able to manage the `as-path-unique-count` to avoid hoping through my nodes when I have a direct route.  Perhaps there is another way to achieve this, but I'm not sure.

### New or Affected Resource(s)

* junos_policyoptions_policy_statement

**Comment by jeremmfr** [comment]
I will take care of adding this.
