### ISSUE TITLE
Feature request: Add configuration for GRE keepalive messages

### ISSUE THREAD

**Issue by AndriiPysmenko** [jeremmfr/terraform-provider-junos#457]
### Description
Generic routing encapsulation (GRE) tunnel interfaces do not have a built-in mechanism for detecting when a tunnel is down. Keepalive messages help the GRE tunnel interfaces to detect when a tunnel is down.

### New Resource

* junos_protocol_oam

### Potential Terraform Configuration

```
set protocols oam gre-tunnel interface gr-0/0/0.100 keepalive-time 10
set protocols oam gre-tunnel interface gr-0/0/0.100 hold-time 30
set protocols oam gre-tunnel interface gr-0/0/0.101 keepalive-time 10
set protocols oam gre-tunnel interface gr-0/0/0.101 hold-time 30
```

### References
https://www.juniper.net/documentation/us/en/software/junos/interfaces-security-devices/topics/topic-map/security-interface-config-gre-keepalive-time.html

**Comment by jeremmfr** [comment]
I will take care of adding this.
