### ISSUE TITLE
Feature Request: Allow passing in SSH key as string rather than file

### ISSUE THREAD

**Issue by evanspaeder** [jeremmfr/terraform-provider-junos#47]
It would be cool if we could support a string for ssh key rather than just a file.  

In my particular use case, I am creating the keys for vSRX in a separate terraform template with the tls_private_key resource.  I currently have to use a local_file resource to write the key to a local file so that the junos provider can access it.  

It would make for a simpler workflow if one could access the private key as a string from remote state.

**Comment by jeremmfr** [comment]
Yes, it's possible, I'll take care of adding it

**Comment by jeremmfr** [comment]
Look release [v1.6.0](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.6.0) for your issue

**Comment by evanspaeder** [comment]
Awesome.  Thanks, @jeremmfr !!
