### ISSUE TITLE
resource junos_security_ike_gateway requires attribute address

### ISSUE THREAD

**Issue by evanspaeder** [jeremmfr/terraform-provider-junos#50]
The resource 'junos_security_ike_gateway' incorrectly requires attribute 'address'. 
When configuring an aggressive tunnel the address attribute would not be configured.

You can see an example of this use case here: https://kb.juniper.net/InfoCenter/index?page=content&id=KB28077&cat=SRX4100&actp=LIST

**Comment by jeremmfr** [comment]
Hi,

The `dynamic` part is not yet integrated. `address` or `dynamic` parameter is required.
I'll take care of adding the dynamic part. Then I could make `address` optional.

**Comment by evanspaeder** [comment]
Awesome.  Thanks @jeremmfr!

**Comment by jeremmfr** [comment]
Look release [v1.7.0](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.7.0)  for your issue
