### ISSUE TITLE
Feature request: support old devices

### ISSUE THREAD

**Issue by aleofreddi** [jeremmfr/terraform-provider-junos#521]
### Description

I was trying to use the terraform-provider-junos with a bunch of EOL'd EX2200 switches running JunOS 12 (which I guess are common for homelabs, as they can be found on eBay for a low price) - in general it worked well, but some configurations didn't apply as they changed with later versions of JunOS (physical interface's `native-vlan-id` and `port-mode`). Follows an example of produced configuration (with fixes):

```
ge-0/0/11 {
    description test-trunk;
    ##
    ## Warning: statement ignored: unsupported platform (ex2200-c-12p-2g)
    ## Warning: native-vlan-id can be specified with flexible-vlan-tagging mode or with interface-mode trunk
    ##
    native-vlan-id 506;
    unit 0 {
        family ethernet-switching {
            port-mode trunk; #<<< In JunOS 12, interface-mode is known as port-mode.
            ##
            ## Warning: statement ignored: unsupported platform (ex2200-c-12p-2g)
            ##
            interface-mode trunk;
            vlan {
                members [ ... ];
            }
            native-vlan-id 506; #<<< This is the right place for native-vlan-id in JunOS 12
        }
    }
}
```

This feature request is to add support for JunOS 12 and have the provider produce the right configuration according to the device version.

### New or Affected Resource(s)

* junos_interface_physical

### Potential Terraform Configuration

No configuration changes.

### References

If there's interest, I can help and put together a PR for this.

**Comment by jeremmfr** [comment]
It seems that switches without ELS use the same parameters.
I will take care of adding additional arguments to cover these cases even if I won't be able to test them.

I prefer to declare additional arguments and let users choose (for example with the data source ´junos_system_information’) instead of trying to detect the right syntax to use and potentially making the wrong choice.
