### ISSUE TITLE
Feature Request - IPSec VPN Traffic Selectors

### ISSUE THREAD

**Issue by evanspaeder** [jeremmfr/terraform-provider-junos#53]
I have some tunnels requiring traffic selectors to be configured on phase 2.  

It seems that the junos_security_ipsec_vpn resource does not currently support traffic selectors as documented by Juniper here: 
https://www.juniper.net/documentation/en_US/junos/topics/topic-map/security-traffic-selectors-in-route-based-vpns.html

**Comment by jeremmfr** [comment]
Look release [v1.8.0](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.8.0)  for your issue
