### ISSUE TITLE
Feature request: Add support for evpn vxlan duplicate-mac-detection on junos_evpn resource.

### ISSUE THREAD

**Issue by michaelburrill** [jeremmfr/terraform-provider-junos#535]
### Description

* Add support for evpn vxlan duplicate-mac-detection on junos_evpn resource. v2.1.2

### New or Affected Resource(s)

* junos_evpn add evpn duplicate-mac-detection

### Potential Terraform Configuration

* resource "junos_evpn" "evpn_vxlan" 
   encapsulation = "vxlan"
      duplicate-mac-detection 
      detection-threshold = "20"
      detection-window    = "5"
      auto-recovery-time = "5"
### References

None that I was able to find.

**Comment by jeremmfr** [comment]
Hi 👋 

I will take care of adding this.
