### ISSUE TITLE
Feature Request - Security settings

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#54]
Would it be possible to start supporting the below security settings for Junos Security devices?

**ALG**
``set security alg dns disable``
``set security alg h323 disable``
``set security alg mgcp disable``
``set security alg msrpc disable``
``set security alg pptp disable``
``set security alg rsh disable``
``set security alg rtsp disable``
``set security alg sccp disable``
``set security alg sip disable``
``set security alg sql disable``
``set security alg sunrpc disable``
``set security alg talk disable``
``set security alg tftp disable``

**FLOW**

``set security flow aging early-ageout 30``
``set security flow aging high-watermark 90``
``set security flow aging low-watermark 80``
``set security flow syn-flood-protection-mode syn-cookie``
``set security flow tcp-session rst-invalidate-session``

**LOG**

``set security log format sd-syslog``
``set security log mode stream``
``set security log rate-cap 500``
``set security log stream remotelog category idp``
``set security log stream remotelog category screen``
``set security log stream remotelog format sd-syslog``
``set security log stream remotelog host 192.168.1.10``
``set security log stream remotelog host port 514``
``set security log stream remotelog severity info``

**FORWARDING**
``set security forwarding-options family inet6 mode flow-based``

Keep up the good work on this very useful provider!
Arjen

**Comment by jeremmfr** [comment]
Look release [v1.8.0](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.8.0)  for your issue
Some of the `alg disable` lines have not been integrated these alg are already disabled by default.
