### ISSUE TITLE
Bug: junos_application Long Update Times

### ISSUE THREAD

**Issue by computeracer** [jeremmfr/terraform-provider-junos#542]
### Terraform and Provider Versions
Terraform 1.5.3
Provider version 2.1.3

### Terraform Configuration Files

```terraform
resource "junos_application" "custom" {
  for_each = {
    for application in local.applications : application.name => application
  }
  name                 = each.value.name
  protocol             = each.value.protocol
  destination_port     = each.value.destination_port
  source_port          = each.value.source_port
  inactivity_timeout   = each.value.inactivity_timeout
  application_protocol = each.value.application_protocol
}
```

### Expected Behavior

With this plan I would expect the state to be updated without needing to perform an update on every resource.

### Actual Behavior

We are performing an update which wants to modify over 130 of these resources and it is taking over 4 hours to complete.

### Steps to Reproduce

1. `terraform apply` the resource with 1.33.0
2. Update with 2.1.3 using `terraform plan/apply`

### Additional Context
Since the state has been already "upgraded" to version 2 with a plan performed it seems to skip any logic there may be when upgrading state from 1.33 to 2.1.3

This is the plan for a single resource:

```
  # module.my_policies.junos_application.custom["smtp_ssl"] will be updated in-place
  ~ resource "junos_application" "custom" {
        id                       = "smtp_ssl"
      - inactivity_timeout       = 0 -> null
      - inactivity_timeout_never = false -> null
        name                     = "smtp_ssl"
        # (2 unchanged attributes hidden)
    }
```

### References

This is an interesting feature of Terraform that may help:
https://developer.hashicorp.com/terraform/plugin/framework/resources/state-upgrade#stateupgrader-with-priorschema

**Comment by jeremmfr** [comment]
Hi :wave:

It's not a bug, this plan appears because you do not refresh resources (you launch `terraform plan` or `terraform apply` with argument `-refresh=false`)

In v2, I started updating the Terraform plugin used by resources from `terraform-plugin-sdk` to `terraform-plugin-framework`. This update needs to update the value of not used optional attributes from zero value to null value, and it's done in `Read` function when Terraform launches a resources refresh.  
`stateupgrader` is useful when updating the resource schema (for example when need to replace the type of an attribute). But in this case, only update value of not used optional attributes is required (done by `Read`).

So you need to do not use `-refresh=fasle` or launch `terraform apply -refresh-only` after updating the provider to a version where the Terraform plugin used by the resource has been updated.

**Comment by computeracer** [comment]
@jeremmfr as always thank you so much for the quick and thorough reply. Refresh is not an option at this time with our team because of the large amount of resources we have deployed to our firewalls and their unreliable internet connections. With the many resources a refresh takes a very long time and can cause issues with the deployment. We depend on plans against the state without refreshes to deploy small batches of changes that can be deployed more quickly and have less of a chance of being interrupted.

I wonder if the use of the schema versions and stateupgrader as linked in the description could perform a migration prior to the plan to address these changes in state rather than trying to read/refresh them which takes a long time in our environment. Let me try a few experiments locally to see if this may be an option.

Thank you for the support!

**Comment by jeremmfr** [comment]
`stateupgrader` would be a solution and could be used to change the values but this would add a lot of complexity in the provider code to provide little gain.

If there are too many resources to refresh, you can also add the `-target` argument to `terraform apply -refresh-only` to reduce the number of affected resources.

Another solution to update the values in Terraform state without launch refresh (`Read`) would be to use the provider arguments `fake_create_with_setfile` and `fake_update_also` when launch the command `terraform update` and without send/apply the generated "set" file to launch modify of new values in Terraform state without connecting to devices.
