### ISSUE TITLE
Feature request: Adding interfaces to a bridge domain in the resource junos_bridge_domain

### ISSUE THREAD

**Issue by Vokunne** [jeremmfr/terraform-provider-junos#548]
### Description

I'm trying to create a bridge domain on MX150 using resource junos_bridge_domain. Unfortunately, this resource doesn't have an option to link router's interfaces to the bridge domain. So, in order to complete bridge domain configuration you have to add necessary interfaces manually in CLI. It'd be great if there was an option to add interfaces in the resource directly.

### New or Affected Resource(s)

junos_bridge_domain

### Potential Terraform Configuration

resource "junos_bridge_domain" "bd-1" {
    name = "bd-1"
    routing_instance = "vswitch-1"
    routing_interface = "irb.5"
    interface = ["ge-0/0/0", "ge-0/0/1", "ge-0/0/2"]  <- requested feature
    vlan_id = "5"
    domain_type_bridge = true
}
### References

https://www.juniper.net/documentation/us/en/software/junos/bridging-learning/topics/task/layer-2-services-bridge-domains-configuring.html

**Comment by jeremmfr** [comment]
Hi 👋 

I will take care of adding this.

**Comment by Vokunne** [comment]
Hi @jeremmfr 
Thank you very much indeed!
