### ISSUE TITLE
Feature request: Add possibility to configure name of the routing instance through which the name server is reachable.

### ISSUE THREAD

**Issue by AndriiPysmenko** [jeremmfr/terraform-provider-junos#561]
### Description

Configure the name of the routing instance through which the name server is reachable.

### New or Affected Resource(s)

junos_system

### Potential Terraform Configuration
 
```hcl
dns {
    name_server = 192.0.2.10, 
    routing-instance = mgmt_junos
}
```

### References
https://www.juniper.net/documentation/us/en/software/junos/junos-overview/topics/ref/statement/name-server-edit-system.html

**Comment by jeremmfr** [comment]
Hi 👋 

I'll take care of adding an argument to configure the routing instance.
