### ISSUE TITLE
Bug: junos_system resource unauthorized character

### ISSUE THREAD

**Issue by arjenvri** [jeremmfr/terraform-provider-junos#570]
### Terraform and Provider Versions
2.3.0

After upgrading to Junos Terraform provider 2.3.0 i am receiving an error on the validation of ciphers within the `junos_system` resource. It seems to fail on the @ sign while actually these are valid juniper ciphers.

```terraform
│ Error: Invalid String Character
│ 
│   with junos_system.this,
│   on settings.tf line 70, in resource "junos_system" "this":
│   70:       ciphers           = ["aes128-gcm@openssh.com", "aes256-gcm@openssh.com", "aes128-ctr"]
│ 
│ string has an unauthorized character: '@'
```

**Comment by jeremmfr** [comment]
Hi 👋 

Thank you for raising this issue. I'll take care of fixing it quickly.
