### ISSUE TITLE
Feature request: add support for multi-chassis

### ISSUE THREAD

**Issue by NikitaPuglachenko** [jeremmfr/terraform-provider-junos#576]
### Description
Add support for multi-chassis

### New or Affected Resource(s)
New:
`junos_multi_chassis`
`junos_multi_chassis_peer`

### Potential Terraform Configuration
```hcl
resource "junos_multi_chassis" "multi_chassis" {
  mc_lag {                       # Optional, Block
    comparison_delay_time = 1    # Optional, Number, (5..600 seconds)
  }
}

resource "junos_multi_chassis_peer" "multi_chassis_peer_demo" {
  name           = "192.0.2.5"   # Required, String
  icl-down-delay = 1             # Optional, Number, (1..6000 seconds)
  interface      = "ae1"         # Optional, String
}
```

### References
https://www.juniper.net/documentation/us/en/software/junos/mc-lag/topics/ref/statement/multi-chassis-qfx-series.html
https://www.juniper.net/documentation/us/en/software/junos/mc-lag/topics/ref/statement/multi-chassis-protection.html

**Comment by jeremmfr** [comment]
Hi 👋

I will take care of adding this.
