### ISSUE TITLE
Feature Request - Add arguments to junos_firewall_filter resource 

### ISSUE THREAD

**Issue by dlucasintouch** [jeremmfr/terraform-provider-junos#58]
Would it be possible to add support for `icmp_code` and `icmp_code_except` arguments within the `from` block of `junos_firewall_filter` ?

**Comment by jeremmfr** [comment]
Look release [v1.8.0](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.8.0) for your issue
