### ISSUE TITLE
Feature request: serial secondary cluster node

### ISSUE THREAD

**Issue by arjenvri** [jeremmfr/terraform-provider-junos#587]
### Description
Would it be possible to expand the current system information datasource to provide the serial number of the secondary node in a chassis cluster?

### New or Affected Resource(s)
* junos_system_information

**Comment by arjenvri** [comment]
thank you for that suggestion and your time! In our case we connect only using the shared cluster ip for administrative reasons. 
Sorry for confusing my request, but i hope you are willing to consider supporting a new data source for show chassis hardware that contains the chassis serial of all nodes.

 ```
> show chassis hardware
node0:
--------------------------------------------------------------------------
Hardware inventory:
Item             Version  Part number  Serial number     Description
Chassis                                JNXXXXXXX     SRXx00
...
node1:
--------------------------------------------------------------------------
Hardware inventory:
Item             Version  Part number  Serial number     Description
Chassis                                JNXXXXXXX     SRXx00
...
```

**Comment by jeremmfr** [comment]
Hi :wave:

After some tests, a RPC request `<get-chassis-inventory>` equivalent to the command `show chassis hardware` can provide a data source.

I'll take care of adding that.
