### ISSUE TITLE
Feature request: removing Conflict Configuration Error when conflicted variable is set to null

### ISSUE THREAD

**Issue by lotusnoir** [jeremmfr/terraform-provider-junos#611]
Hello, im writting a module to use this provider
I have an issue with the variables that cannot be set together

exemple for junos_interface_physical ressource

```
│ Error: Conflict Configuration Error
│ 
│   with module.fwv-ang49-12.junos_interface_physical.this,
│   on ../../modules/terraform-module-srx_config/interfaces.tf line 2, in resource "junos_interface_physical" "this":
│    2: resource "junos_interface_physical" "this" {
│ 
│ only one of ether_opts, gigether_opts or parent_ether_opts block can be specified
```

I've declared in my ressource

```
resource "junos_interface_physical" "this" {
  for_each = var.interfaces_physical
  name     = each.key

  no_disable_on_destroy = each.value.no_disable_on_destroy
  description           = each.value.description
  disable               = each.value.disable
  encapsulation         = each.value.encapsulation

  dynamic "ether_opts" {
    for_each = each.value.ether_opts != null && each.value.parent_ether_opts == null ? [each.value.ether_opts] : []
    iterator = ether
    content {
      ae_8023ad        = ether.value.ae_8023ad
      auto_negotiation = ether.value.auto_negotiation
      #no_auto_negotiation= ether.value.no_auto_negotiation
    }
 }

  dynamic "parent_ether_opts" {
     for_each = each.value.parent_ether_opts != null && each.value.ether_opts == null ? [each.value.parent_ether_opts] : []                              
      iterator = popts
  
      content {
        flow_control = popts.value.flow_control
        #no_flow_control = popts.value.no_flow_control
    }     
 }
}
```
 
and on the variables

```
variable "interfaces_physical" {
  type = map(object({
    no_disable_on_destroy = optional(bool)
    description           = optional(string)
    disable               = optional(bool)
    encapsulation         = optional(string)
    ether_opts = optional(object({
      ae_8023ad           = optional(string)
      auto_negotiation    = optional(bool)
      no_auto_negotiation = optional(bool)
      flow_control        = optional(bool)
      no_flow_control     = optional(bool)
      loopback            = optional(bool)
      no_loopback         = optional(bool)
      redundant_parent    = optional(string)
    }))
    parent_ether_opts = optional(object({
      flow_control    = optional(bool)
      no_flow_control = optional(bool)
  }))
  default = {}
}
```

Do you see a way to bypass this error ? do you think you should update your code in order to accept this blocks together if they are equals to null ?
I also have to same question for all the opposite vars loopback/no_loopback, flow/no_flow etc...
Thanks in advance

**Comment by jeremmfr** [comment]
Hi 👋

Thank you for raising this issue.  
After testing your example, I discovered that the received resource config by the resource config validator can have **unknown** value for all configured attributes in modules whatever the module variable value and the final value for resources attributes/blocks. With a difference for single block, in this case block is set to known with all configured block attributes in modules to unknown value.  
Unfortunately, in resource validator, I not considered this potential case and I will have to add a skip on conflict check when have :

- a attribute with unknown value (value could be null after the config validator call)
- a single block with null or unknown values in all block attributes (which means that the block could be null after the config validator call)

I take care of fix this and other potential same cases on other resources.
