### ISSUE TITLE
Group option in configuration

### ISSUE THREAD

**Issue by wuzhangyouhe** [jeremmfr/terraform-provider-junos#66]
Is it possible to add group option to this plug-in please ? 
Because most of customer are using JUNOS with groups hierarchic levels. 

For example, 
```
set groups service-A protocols bgp groups customer-A type internal
set protocols bgp apply-groups service-A
```
This could help network administrators to separate each services into groups and managing by provisioning easier. 
Once the service-A is no longer needed, that makes configuration management clearly.
```
delete protocols bgp apply-groups servcie-A
delete groups service-A
```
Thanks so much!

**Comment by jeremmfr** [comment]
I don't see the point of adding support for `groups`.

With Terraform, we already have the possibility to separate the configurations by Terraform config (state), files in config, Terraform modules.
For the deletion, it is enough to launch a `terraform apply` after having deleted the file or the modules or a `terraform destroy` if the configuration is separated in several different config (state).

Adding `groups` will only add complexity without providing any real value compared to what is possible with Terraform.
