### ISSUE TITLE
Support static IPv6 Routes

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#67]
Would it be possible to support adding IPv6 static routes?
Adding IPv6 routes with gateway at this moment results in invalid address errors.

```
resource junos_static_route "default_route" {
   destination = "::/0"
   qualified_next_hop {
    next_hop = "fe80::1"
  }
}
```

**Comment by jeremmfr** [comment]
Look release [v1.9.0](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.9.0) for your issue
