### ISSUE TITLE
Feature request: add "remote-vtep-list" option for resource junos_routing_instance

### ISSUE THREAD

**Issue by Vokunne** [jeremmfr/terraform-provider-junos#673]
### Description

Hi there, 

this feature request is related to #672. 
I found out that configuration "static-remote-vtep-list" option in a vxlan block in a "junos_bridge_domain" resource is also required a "remote-vtep-list" configuration for "junos_routing_instance". It's necessary when the type of routing instance is "virtual-switch"

### New or Affected Resource(s)

junos_routing_instance

### Example Junos Configuration

```txt
routing-instances {
    rt1 {
        vtep-source-interface lo0.0;
        remote-vtep-list [ 10.1.1.1 10.1.1.2 ];
        instance-type virtual-switch;
        bridge-domains {
            bd1 {
                vlan-id 5;
                vxlan {
                    vni 500005;
                    ingress-node-replication;
                    static-remote-vtep-list [ 10.1.1.1 10.1.1.2 ];
                }
            }
```

### Potential Terraform Configuration

```hcl
resource "junos_routing_instance" "rt1" {
  name                  = "rt1"
  type                  = "virtual-switch"
  description           = "vSwitch routing instance for static VXLANs"
  vtep_source_interface = "lo0.0"
  remote_vtep_ist       = [ 10.1.1.1, 10.1.1.2 ]
```

### References

From Junos docs:
"On some platforms, you can use this statement with the static-remote-vtep-list statement to also configure remote VTEPs at the VLAN or bridge domain level. When you use the static-remote-vtep-list option, you must configure the remote-vtep-list statement to specify the remote VTEPs at the global level as follows:

In an L2 routing instance of type virtual-switch at the [edit routing-instances name] hierarchy level.

In the default switch instance at the [edit switch-options] hierarchy level."

Link to Junos docs:
https://www.juniper.net/documentation/us/en/software/junos/cli-reference/topics/ref/statement/remote-vtep-list-routing-instances.html

**Comment by jeremmfr** [comment]
Hi 👋

I will take care of adding this.

**Comment by Vokunne** [comment]
@jeremmfr thanks a lot!
