### ISSUE TITLE
Feature : add transport protocol on junos_security_log_stream

### ISSUE THREAD

**Issue by lotusnoir** [jeremmfr/terraform-provider-junos#675]
Hello, im currently configuring a security log stream and i realized that we can't chose the transport protocol on the ressource  junos_security_log_stream like:
```
stream Syslog {
    format syslog;
    category flow;
    category content-security;
    host {
        10.1.80.54;
        port 514;
    }
    transport {
        protocol udp;
    }
}
```

Can you add it please ?
Thanks in advance

**Comment by jeremmfr** [comment]
Hi 👋

I will take care of adding this.
