### ISSUE TITLE
Feature request: Manage junos_application like junos_security_address_book

### ISSUE THREAD

**Issue by lotusnoir** [jeremmfr/terraform-provider-junos#694]
hello,
I start to have a lot of declared application on my srx, and because 1 port = 1 terraform ressource, that's making the plan / apply extremly slow.
Is it possible to declare the applications ports not separetly but like block set in order to have just 1 ressource to declare them all ?
Thanks in advance

**Comment by jeremmfr** [comment]
Hi :wave:

A resource defining Junos `applications` block entirely is acceptable.
However, it will conflict with actual resources `junos_application` and `junos_application_set`.
I will take care of adding this.
