### ISSUE TITLE
Add interface option to qualified next hop on static route

### ISSUE THREAD

**Issue by tagur87** [jeremmfr/terraform-provider-junos#71]
Missing the `interface` option on the `qualified_next_hop` portion of the static route resource.

Would allow a command like this to be done with resource.

```
set routing-instances test routing-options rib DATA.inet6.0 static route 1234:1234::/32 qualified-next-hop 1234:1234:11:1::1 interface ge-0/0/0.123
```

**Comment by tagur87** [comment]
Please assign to me as I have the code mostly complete for this enhancement.

Thanks!

**Comment by jeremmfr** [comment]
> Please assign to me as I have the code mostly complete for this enhancement.
> 
> Thanks!

Ok, I assigned it to you

**Comment by jeremmfr** [comment]
Look release [v1.10.0](https://github.com/jeremmfr/terraform-provider-junos/releases/tag/v1.10.0) for your issue
