### ISSUE TITLE
Netconf - high number of session created

### ISSUE THREAD

**Issue by Cidotis** [jeremmfr/terraform-provider-junos#87]
Hello,
Thank you very much for your work on this provider, this is really useful. I've been using it in a lab to test some device configuration and it works really well. 

Under some circumstances when having a lot of resources I did hit some Junos netconf session rate-limits, or was blocked by some IDP/IPS SSH brute force detection.
I don't have any experience with Go yet, however reading through the code it looks like a new session is created for every resource. Is my understanding correct, or am I doing something wrong ?

Is there a way to re-use the same Netconf/SSH session, or limit the number of sessions being initiated ?

Thank you very much.

Some additional details:
Faced some "connection timeout" with Terraform v0.14.3, jeremmfr/junos 1.11.0, a vSRX running Junos 19.3, with more than 60 resources configured and latency to the target vSRX over 50ms. I'm still investigating the exact circumstances, but I was able to relate this to the number of SSH/Netconf sessions.

**Comment by jeremmfr** [comment]
The terraform sdk doesn't permit me to re-use a shared netconf/ssh session.

The provider establishes 1 or 2 sessions on the device per action per resource and terraform launches 10 simultaneous provider actions (see https://www.terraform.io/docs/internals/graph.html#walking-the-graph)

Have you tried running terraform with the `-parallelism 1` argument ?

**Comment by jeremmfr** [comment]
Additionally of `parrellism` argument, I will look to:
- reduce the number of ssh / netconf sessions to 1 (not 2) per action per resource
- add an optional argument to sleep X seconds after closing the ssh session.
