### ISSUE TITLE
Predefined Junos Applications

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#93]
Is there a way to reference one of the builtin junos applications in security policies?

Or defining the builtin applications without setting the application specific parameters so we can refer to them as builtin?

`show configuration groups junos-defaults applications`

**Comment by jeremmfr** [comment]
Hello, 

You can use the application name directly, for example with the default application `junos-ssh`:
```hcl
resource junos_security_policy "demo_policy" {
  from_zone = "trust"
  to_zone   = "untrust"
  policy {
    name                      = "allow_ssh"
    match_source_address      = ["any"]
    match_destination_address = ["any"]
    match_application         = ["junos-ssh"]
  }
}
```

**Comment by a-d-v** [comment]
thank you so much for your kind help! Somehow i totally missed that! :)
