### ISSUE TITLE
Support additional security algs

### ISSUE THREAD

**Issue by a-d-v** [jeremmfr/terraform-provider-junos#95]
Would it be possible to support disabling the H323, MGCP, RTSP, SCCP and SIP security ALG that are enable by default?

thank you

**Comment by a-d-v** [comment]
Submitted pull request #94

**Comment by jeremmfr** [comment]
Ok, this is not enable by default for me (so I had not seen the usefulness) but in fact it's in according to the model (cf [kb](https://kb.juniper.net/InfoCenter/index?page=content&id=KB25546&actp=METADATA)).
I'll to watch the PR
